# Image from https://hub.docker.com/_/php/
image: node:latest

cache:
  paths:
  - node_modules/

before_script:
  - npm install hexo-cli -g
  - npm install hexo-deployer-ftpsync --save
  - npm install
  - sed -i ‘s/SECRET_KEY/'"$FTP_SECRET_KEY"'/g’ _config.yml

test:base:
  script:
    - hexo generate
    - hexo deploy