# Image from https://hub.docker.com/_/php/
image: node:latest

cache:
  paths:
  - node_modules/

before_script:
  - sed 's/SECRET_KEY/'$FTP_SECRET_KEY'/g' beta.config.yml.dist > _config.yml
  - npm install hexo-cli -g
  - npm install hexo-deployer-ftpsync --save
  - npm install hexo-all-minifier --save
  - npm install

test:base:
  script:
    - hexo generate
    - hexo deploy