# Hexo Configuration
## Docs: http://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: Tyneo Consulting
alternateName: Tyneo - Conseil et expertise outils PMO
subtitle: Conseil et expertise sur les outils PMO
description: Conseil et expertise sur les outils PMO
author: Samuel Kauffmann
language:
  - fr
  - en
  - pl
timezone: Europe/Paris


# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
#url: http://beta.tyneo.net/
root: /
url: https://tyneo.net/
#root: /v2/
permalink: /blog/:year/:month/:day/:title/
permalink_defaults:

# Directory
source_dir: source
public_dir: public
tag_dir: blog/tags
archive_dir: blog
category_dir: blog/categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link: true # Open external links in new tab
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: true
highlight:
  enable: true
  line_number: true
  auto_detect: true
  tab_replace:

# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: DD/MM/YYYY
time_format: HH:mm:ss

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Extensions
## Plugins: http://hexo.io/plugins/
## Themes: http://hexo.io/themes/
theme: hexo-tyneo-theme

include:
  - .htaccess
exclude_generators:
  - index
  - fr/projects.ejs

#Hexo-all-minifier
html_minifier:
  enable: false
  exclude:
    - 'fr/contact.ejs'
    - 'fr/about/contact.html'
    - 'fr/about/contact.ejs'
    - '*contact*'
    - 'fr/about/contact.*'
    - 'en/about/contact.*'
    - 'pl/about/contact.*'
css_minifier:
  enable: false
  exclude:
    - '*.min.css'
js_minifier:
  enable: false
  mangle: true
  output:
  compress:
  exclude:
    - '*.min.js'
    - fr/contact.ejs
    - en/contact.ejs
    - pl/contact.ejs
image_minifier:
  enable: false
  interlaced: false
  multipass: false
  optimizationLevel: 2
  pngquant: false
  progressive: false


sitemap:
    path: fr/sitemap.xml

alias:
  /fr/contact.html: /fr/about/contact.html
  /fr/company.html: /fr/about
  /fr/planisware.html: /fr/epm-ppm-solutions.html
  /fr/projects.html: /fr/epm-ppm-solutions.html
  /fr/requirements.html: /fr/rmt-solutions.html
  /fr/publications.html: /fr/events.html

  /fr/about/planisware.html: /fr/tools/epm-ppm/planisware.html
  /fr/training/planisware_getting_started/index.html: /fr/training/planisware_getting_started.html
  /fr/training/planisware_mod_pm/index.html: /fr/training/planisware_mod_pm.html
  /fr/training/planisware_admin/index.html: /fr/training/planisware_admin.html
  /fr/training/planisware_integrator/index.html: /fr/training/planisware_integrator.html
  /fr/training/planisware_learn_ojs/index.html: /fr/training/planisware_learn_ojs.html
  /fr/training/caliber_requirement_management/index.html: /fr/training/caliber_requirement_management.html
  /fr/training/caliber_administrator/index.html: /fr/training/caliber_administrator.html

  /blog/category/UnMoisUneAstucePlanisware/index.html:	/blog/category/Astuce/index.html

  /pl/index.html: /pl/epm-ppm-solutions.html

  /bin/index.html: /
  /: /fr/
