translate:
  url: :base_culture/:something1
  param: { module: translate, action: translate, no_sitemap: true }
  requirements: { base_culture: [fr,en] }
translate2:
  url: :base_culture/:something1/:something2
  param: { module: translate, action: translate, no_sitemap: true }
  requirements: { base_culture: [fr,en] }
  
welcome:
  url: home.html
  param: { module: page, default_template: WelcomePage, priority: 0.8 }
  requirements: { device_type: desktop }
projects:
  url: projects.html
  param: { module: page, default_template: ProjectsPage, priority: 1.0 }
  requirements: { device_type: desktop }
requirements:
  url: requirements.html
  param: { module: page, default_template: RequirementsPage, priority: 1.0 }
  requirements: { device_type: desktop }
about_us:
  url: company.html
  param: { module: page, default_template: TyneoPage, priority: 0.5 }
  requirements: { device_type: desktop }
partners:
  url: company/partners.html
  param: { module: page, default_template: PartnerPage, priority: 0.5, no_sitemap: true }
  requirements: { device_type: desktop }
about_planisware:
  url: about/planisware.html
  param: { module: page, default_template: AboutPlaniswarePage, priority: 0.8 }
  requirements: { device_type: desktop }
about_caliber:
  url: about/caliber.html
  param: { module: redirection, action: redirect, next: "http://www.tyneo-consulting.fr/fr/tool/requirement/caliber", no_sitemap: true }
publications:
  url: publications.html
  param: { module: page, default_template: PublicationsPage, priority: 0.4 }
  requirements: { device_type: desktop }
vcard:
  url: contact.html
  param: { module: contact, action: vcard, no_sitemap: true }
  requirements: { alt: vcard }
contact:
  url: contact.html
  param: { module: contact, default_template: ContactPage, method: GET, priority: 0.7, changefreq: yearly }
  requirements: { alt: html, device_type: desktop }
contact_sendmessage:
  url: contact.html
  param: { module: contact, action: sendMessage, default_template: ContactMessageSendedPage, method: POST, no_sitemap: true }
  requirements: { alt: html, device_type: desktop }
mentions:
  url: mentions.html
  param: { module: page, default_template: MentionsPage, priority: 0.1, changefreq: never }
  requirements: { alt: html, device_type: desktop }
sitemap:
  url: sitemap.html
  param: { module: sitemap, default_template: SitemapPage, priority: 0.1, changefreq: yearly }
  requirements: { alt: html, device_type: desktop }
sitemap_xml:
  url: sitemap.xml
  param: { module: sitemap, action: xmlSitemap, default_alt: xml, no_sitemap: true }
  requirements: { alt: xml, device_type: desktop }
  

############################################################
# Training routes
############################################################
trainings_sitemap_xml:
  url: training/sitemap.xml
  param: { module: training, action: xmlSitemap, default_alt: xml, no_sitemap: true }
  requirements: { alt: xml, device_type: desktop }
trainings:
  url: training
  param: { module: training, default_template: TrainingList, action: showTrainings, priority: 1, changefreq: yearly}
  requirements: { alt: html, device_type: desktop }
training_contact:
  url: training/contact.html
  param: { module: training, default_template: ContactPage, action: showTrainings, method: GET}
  requirements: { alt: html, device_type: desktop }
training_contact_sendmessage:
  url: training/contact.html
  param: { module: training, action: sendMessage, default_template: ContactMessageSendedPage, method: POST, no_sitemap: true }
  requirements: { alt: html, device_type: desktop }
training:
  url: training/:slug
  param: { module: training, default_template: Training, action: showTraining, no_sitemap: true }
  requirements: { alt: html, device_type: desktop }
############################################################


############################################################
# Tool routes
############################################################
tools_sitemap_xml:
  url: tool/sitemap.xml
  param: { module: tool, action: xmlSitemap, default_alt: xml, no_sitemap: true }
  requirements: { alt: xml, device_type: desktop }
tools:
  url: tool/:type
  param: { module: tool, default_template: toolList, action: showTools}
  requirements: { alt: html, device_type: desktop } 
tool:
  url: tool/:type/:slug
  param: { module: tool, default_template: tool, action: showTool, no_sitemap: true }
  requirements: { alt: html, device_type: desktop }  
############################################################


############################################################
# Events routes
############################################################
events:
  url: event/
  param: { module: event, default_template: Events, action: showEvents}
  requirements: { alt: html, device_type: desktop }
event_register:
  url: event/new
  param: { module: event, default_template: Register, action: registerEvent, no_sitemap: true }
  requirements: { alt: html, device_type: desktop }
event:
  url: event/:id
  param: { module: event, default_template: Event, action: showEvent, no_sitemap: true }
  requirements: { alt: html, device_type: desktop }
event_update:
  url: event/:id/update
  param: { module: event, default_template: Update, action: updateEvent, no_sitemap: true }
  requirements: { alt: html, device_type: desktop }
event_delete:
  url: event/:id/delete
  param: { module: event, default_template: Delete, action: deleteEvent, no_sitemap: true }
  requirements: { alt: html, device_type: desktop }
############################################################

############################################################
# Newsletter routes
############################################################
newsletter_register:
  url: newsletter/register.html
  param: { module: newsletter, default_template: RegisterPage, method: GET}
  requirements: { alt: html, device_type: desktop }
newsletter_subscribe:
  url: newsletter/register.html
  param: { module: newsletter, action: subscribe, default_template: RegisterPage, method: POST, no_sitemap: true }
  requirements: { alt: html, device_type: desktop }
newsletter_setting:
  url: newsletter/setting.html
  param: { module: newsletter, action: setting, default_template: SettingPage, method: GET, no_sitemap: true }
  requirements: { alt: html, device_type: desktop }
newsletter_setting_update:
  url: newsletter/setting.html
  param: { module: newsletter, action: settingUpdate, default_template: SettingPage, method: POST, no_sitemap: true }
  requirements: { alt: html, device_type: desktop }
############################################################


style:
  url: style.html
  param: { module: page, default_template: StylePage, priority: 0.1, changefreq: never, no_sitemap: true }
  requirements: { alt: html, device_type: desktop } 


welcome_mobile:
  url: :all
  param: { module: page, default_template: MobilePage, default_layout: mobile_layout, no_sitemap: true }
  requirements: { device_type: mobile }