<?php
/**
 * Account
 * Generated by Tyneo Base Tools
 *
 * @package     model
 * @author      Samuel Kauffmann <skauffmann@tyneo.net>
 * @copyright   Copyright (c) 2011, Samuel Kauffmann
 * @link        http://www.tyneo.net
 * @filesource	BaseAccountManager.class.php
 */
namespace model;

/**
 * This class provides an object representation of a Account.
 *
 * @author		Samuel Kauffmann <skauffmann@tyneo.net>
 * @version		1.0
 */
class Account extends Base\BaseAccount {

	/**
	 * Set up Account object
	 */
	protected function configure() {

	}
}
