<?php
/**
 * Accounting
 * Generated by Tyneo Base Tools
 *
 * @package     model
 * @author      Samuel Kauffmann <skauffmann@tyneo.net>
 * @copyright   Copyright (c) 2011, Samuel Kauffmann
 * @link        http://www.tyneo.net
 * @filesource	BaseAccountingManager.class.php
 */
namespace model;

/**
 * This class provides an object representation of a Accounting.
 *
 * @author		Samuel Kauffmann <skauffmann@tyneo.net>
 * @version		1.0
 */
class Accounting extends Base\BaseAccounting {

	/**
	 * Set up Accounting object
	 */
	protected function configure() {

	}
}
