<?php
/**
 * BlgPosts
 * Generated by Tyneo Base Tools
 *
 * @package     model
 * @author      Samuel Kauffmann <skauffmann@tyneo.net>
 * @copyright   Copyright (c) 2011, Samuel Kauffmann
 * @link        http://www.tyneo.net
 * @filesource	BaseBlgPostsManager.class.php
 */
namespace model;

/**
 * This class provides an object representation of a BlgPosts.
 *
 * @author		Samuel Kauffmann <skauffmann@tyneo.net>
 * @version		1.0
 */
class BlgPosts extends Base\BaseBlgPosts {

	/**
	 * Set up BlgPosts object
	 */
	protected function configure() {

	}
}
