<?php
/**
 * Commentmeta
 * Generated by Tyneo Base Tools
 *
 * @package     model
 * @author      Samuel Kauffmann <skauffmann@tyneo.net>
 * @copyright   Copyright (c) 2011, Samuel Kauffmann
 * @link        http://www.tyneo.net
 * @filesource BaseCommentmetaManager.class.php
 */
namespace model;

/**
 * This class provides an object representation of a Commentmeta.
 *
 * @author  Samuel Kauffmann <skauffmann@tyneo.net>
 * @version  1.0
 */
class Commentmeta extends Base\BaseCommentmeta {

	/**
	 * Set up Commentmeta object
	 */
	protected function configure() {

	}
}
