<?php
/**
 * Comments
 * Generated by Tyneo Base Tools
 *
 * @package     model
 * @author      Samuel Kauffmann <skauffmann@tyneo.net>
 * @copyright   Copyright (c) 2011, Samuel Kauffmann
 * @link        http://www.tyneo.net
 * @filesource BaseCommentsManager.class.php
 */
namespace model;

/**
 * This class provides an object representation of a Comments.
 *
 * @author  Samuel Kauffmann <skauffmann@tyneo.net>
 * @version  1.0
 */
class Comments extends Base\BaseComments {

	/**
	 * Set up Comments object
	 */
	protected function configure() {

	}
}
