<?php
/**
 * Company
 * Generated by Tyneo Base Tools
 *
 * @package     model
 * @author      Samuel Kauffmann <skauffmann@tyneo.net>
 * @copyright   Copyright (c) 2011, Samuel Kauffmann
 * @link        http://www.tyneo.net
 * @filesource	BaseCompanyManager.class.php
 */
namespace model;

/**
 * This class provides an object representation of a Company.
 *
 * @author		Samuel Kauffmann <skauffmann@tyneo.net>
 * @version		1.0
 */
class Company extends Base\BaseCompany {

	/**
	 * Set up Company object
	 */
	protected function configure() {

	}
}
