<?php
/**
 * Contact
 * Generated by Tyneo Base Tools
 *
 * @package     model
 * @author      Samuel Kauffmann <skauffmann@tyneo.net>
 * @copyright   Copyright (c) 2011, Samuel Kauffmann
 * @link        http://www.tyneo.net
 * @filesource	BaseContactManager.class.php
 */
namespace model;

/**
 * This class provides an object representation of a Contact.
 *
 * @author		Samuel Kauffmann <skauffmann@tyneo.net>
 * @version		1.0
 */
class Contact extends Base\BaseContact {

	/**
	 * Set up Contact object
	 */
	protected function configure() {

	}
}
