<?php
/**
 * Contract
 * Generated by Tyneo Base Tools
 *
 * @package     model
 * @author      Samuel Kauffmann <skauffmann@tyneo.net>
 * @copyright   Copyright (c) 2011, Samuel Kauffmann
 * @link        http://www.tyneo.net
 * @filesource	BaseContractManager.class.php
 */
namespace model;

/**
 * This class provides an object representation of a Contract.
 *
 * @author		Samuel Kauffmann <skauffmann@tyneo.net>
 * @version		1.0
 */
class Contract extends Base\BaseContract {

	/**
	 * Set up Contract object
	 */
	protected function configure() {

	}
}
