<?php
/**
 * Editor
 * Generated by Tyneo Base Tools
 *
 * @package     model
 * @author      Samuel Kauffmann <skauffmann@tyneo.net>
 * @copyright   Copyright (c) 2011, Samuel Kauffmann
 * @link        http://www.tyneo.net
 * @filesource	BaseEditorManager.class.php
 */
namespace model;

/**
 * This class provides an object representation of a Editor.
 *
 * @author		Samuel Kauffmann <skauffmann@tyneo.net>
 * @version		1.0
 */
class Editor extends Base\BaseEditor {

	/**
	 * Set up Editor object
	 */
	protected function configure() {

	}
}
