<?php
/**
 * Event
 * Generated by Tyneo Base Tools
 *
 * @package     model
 * @author      Samuel Kauffmann <skauffmann@tyneo.net>
 * @copyright   Copyright (c) 2011, Samuel Kauffmann
 * @link        http://www.tyneo.net
 * @filesource	BaseEventManager.class.php
 */
namespace model;

/**
 * This class provides an object representation of a Event.
 *
 * @author		Samuel Kauffmann <skauffmann@tyneo.net>
 * @version		1.0
 */
class Event extends Base\BaseEvent {

	/**
	 * Set up Event object
	 */
	protected function configure() {
		$this->setValidators(array(
			'name'   => new \framework\validator\StringValidator(array('required' => true)),
			'state'   => new \framework\validator\StringValidator(array('required' => true))
		));
	}
	
	public function getShortDescription() {
		return \framework\utility\String::trunchtml($this->getDescription(), 350);
	}
}
