<?php
/**
 * Links
 * Generated by Tyneo Base Tools
 *
 * @package     model
 * @author      Samuel Kauffmann <skauffmann@tyneo.net>
 * @copyright   Copyright (c) 2011, Samuel Kauffmann
 * @link        http://www.tyneo.net
 * @filesource BaseLinksManager.class.php
 */
namespace model;

/**
 * This class provides an object representation of a Links.
 *
 * @author  Samuel Kauffmann <skauffmann@tyneo.net>
 * @version  1.0
 */
class Links extends Base\BaseLinks {

	/**
	 * Set up Links object
	 */
	protected function configure() {

	}
}
