<?php
/**
 * MailingList
 * Generated by Tyneo Base Tools
 *
 * @package     model
 * @author      Samuel Kauffmann <skauffmann@tyneo.net>
 * @copyright   Copyright (c) 2011, Samuel Kauffmann
 * @link        http://www.tyneo.net
 * @filesource	BaseMailingListManager.class.php
 */
namespace model;

/**
 * This class provides an object representation of a MailingList.
 *
 * @author		Samuel Kauffmann <skauffmann@tyneo.net>
 * @version		1.0
 */
class Mailinglist extends Base\BaseMailinglist {

	protected function configure() {
		$this->setValidators(array(
				'mail'   => new \framework\validator\EmailValidator(
						array('required' => true),
						array(
								'invalid' => "L'adresse mail renseigné est invalide.",
								'required' => "L'adresse mail est obligatoire."
						)),
		));
	}

	public function addInterest($item) {
		$interests = $this->getInterest();
		if($this->hasInterest($item) == false) {
			if($interests != "") $this->setInterest($interests.','.$item);
			else $this->setInterest($item);
		}
	}

	public function hasInterest($item) {
		$interests = explode (',', $this->getInterest());
		foreach($interests as $interest) {
			if($interest == $item) return true;
		}
		return false;
	}
	
	public function getFullname() {
		return trim($this->getLastname().' '.$this->getFirstname());		
	}
}