<?php
/**
 * MailingList
 * Generated by Tyneo Base Tools
 *
 * @package     model
 * @author      Samuel Kauffmann <skauffmann@tyneo.net>
 * @copyright   Copyright (c) 2011, Samuel Kauffmann
 * @link        http://www.tyneo.net
 * @filesource	BaseMailingListManager.class.php
 */
namespace model;

/**
 * This class provides manager to manipulate MailingList objects.
 *
 * @author		Samuel Kauffmann <skauffmann@tyneo.net>
 * @version		1.0
 */
class MailinglistManager extends base\BaseMailinglistManager {
	public function __construct() {
		parent::__construct(\framework\ApplicationContext::getInstance());
	}

	public function mailExists($mail) {
		$query = new \framework\query\QueryBuilder();
		$query->addSelectCount(id);
		$query->addTable($this->getTableName());
		$query->addWhere('mail', \framework\query\operator\Operator::EQUAL, $mail);
		return $this->database->execute($query->toSQL()) == "1";
	}
	
	public function getMailinglistByKey($key) {
		$query = new \framework\query\QueryBuilder();
		$query->addSelect($this->getTableName().'.*');
		$query->addTable($this->getTableName());
		$query->addWhere($this->getTableName().'.activation_code', \framework\query\operator\Operator::EQUAL, $key);
		$object = $this->database->queryUniqueObject($query->toSQL());
		if($object != null) {
			return $this->getObjectFromRow($object);
		}
		return null;
	}
}
