<?php
/**
 * Options
 * Generated by Tyneo Base Tools
 *
 * @package     model
 * @author      Samuel Kauffmann <skauffmann@tyneo.net>
 * @copyright   Copyright (c) 2011, Samuel Kauffmann
 * @link        http://www.tyneo.net
 * @filesource BaseOptionsManager.class.php
 */
namespace model;

/**
 * This class provides an object representation of a Options.
 *
 * @author  Samuel Kauffmann <skauffmann@tyneo.net>
 * @version  1.0
 */
class Options extends Base\BaseOptions {

	/**
	 * Set up Options object
	 */
	protected function configure() {

	}
}
