<?php
/**
 * Posts
 * Generated by Tyneo Base Tools
 *
 * @package     model
 * @author      Samuel Kauffmann <skauffmann@tyneo.net>
 * @copyright   Copyright (c) 2011, Samuel Kauffmann
 * @link        http://www.tyneo.net
 * @filesource BasePostsManager.class.php
 */
namespace model;

/**
 * This class provides an object representation of a Posts.
 *
 * @author  Samuel Kauffmann <skauffmann@tyneo.net>
 * @version  1.0
 */
class Posts extends Base\BasePosts {

	/**
	 * Set up Posts object
	 */
	protected function configure() {

	}
	
	public function getTruncatedContent($length) {
		return \framework\utility\String::trunchtml($this->getPostContent(), $length);	
	}
	
	public function getPostDate() {
		$date_display_format = 'd/m/Y';
		$datetime = strtotime(parent::getPostDate());
		$date = date('Y-m-d', $datetime);
		
		if($date == date('Y-m-d')) return 'Aujourd\'hui';
		else if(strtotime($date) == strtotime(date('Y-m-d').' - 1 DAY')) return 'Hier';
		else if(strtotime($date) == strtotime(date('Y-m-d').' - 2 DAY')) return 'Avant hier';
		else return null;
	}
	
	public function getBlogPath() {
$datetime = strtotime(parent::getPostDate());
		return date('Y', $datetime).'/'.date('m', $datetime).'/'.date('d', $datetime).'/'.$this->getPostName();
	}

	public function setId($id) {
		$this->properties->set('id', $id);
		return $this;
	}
}
