<?php
/**
 * Postmeta
 * Generated by Tyneo Base Tools
 *
 * @package     model
 * @author      Samuel Kauffmann <skauffmann@tyneo.net>
 * @copyright   Copyright (c) 2011, Samuel Kauffmann
 * @link        http://www.tyneo.net
 * @filesource BasePostmetaManager.class.php
 */
namespace model;

/**
 * This class provides an object representation of a Postmeta.
 *
 * @author  Samuel Kauffmann <skauffmann@tyneo.net>
 * @version  1.0
 */
class Postmeta extends Base\BasePostmeta {

	/**
	 * Set up Postmeta object
	 */
	protected function configure() {

	}
}
