<?php
/**
 * Profile
 * Generated by Tyneo Base Tools
 *
 * @package     model
 * @author      Samuel Kauffmann <skauffmann@tyneo.net>
 * @copyright   Copyright (c) 2011, Samuel Kauffmann
 * @link        http://www.tyneo.net
 * @filesource	BaseProfileManager.class.php
 */
namespace model;

/**
 * This class provides manager to manipulate Profile objects.
 *
 * @author		Samuel Kauffmann <skauffmann@tyneo.net>
 * @version		1.0
 */
class ProfileManager extends base\BaseProfileManager {
	public function __construct() {
		parent::__construct(\framework\ApplicationContext::getInstance());
	}

	public function getProfilesByUser(User $obj) {
		$query = new \framework\query\QueryBuilder();
		$query->addSelect($this->getTableName().'.*');
		$query->addTable($this->getTableName());
		$query->addJoin('user_profile', 'profile_id', $this->getTableName().'.id');
		$query->addWhere('user_profile.user_id', \framework\query\operator\Operator::EQUAL, $obj->getId());
		$results = $this->database->query($query->toSQL());
		return $this->getObjectsFromResult($results);
	}
	
	public function addProfiles(array $names, User $user) {
		$profiles = $this->getProfiles();
		$ids = array();
		foreach($profiles as $profile) {
			if(in_array($profile->getName(), $names)) {
				$ids[] = $profile->getId();
			}
		}
		foreach($ids as $id) {
			$query = new \framework\query\CreateBuilder('user_profile');
			$query->setField('user_id', $user->getId());
			$query->setField('profile_id', $id);
			$this->database->execute($query->toSQL());
		}
	}
}
