<?php
/**
 * Profile
 * Generated by Tyneo Base Tools
 *
 * @package     model
 * @author      Samuel Kauffmann <skauffmann@tyneo.net>
 * @copyright   Copyright (c) 2011, Samuel Kauffmann
 * @link        http://www.tyneo.net
 * @filesource	BaseProfileManager.class.php
 */
namespace model;

/**
 * This class provides an object representation of a Profile.
 *
 * @author		Samuel Kauffmann <skauffmann@tyneo.net>
 * @version		1.0
 */
class Profile extends Base\BaseProfile {

	/**
	 * Set up Profile object
	 */
	protected function configure() {

	}
	
	public function getPermissions() {
		$permissions = parent::getPermissions();
		$arrayList = preg_split('/,/', $permissions);
		return $arrayList;
	}
	
	public function setPermissions($arrayList) {
		if(is_array($arrayList)) {
			$permissions = implode(',', $arrayList);
			return parent::setPermissions($permissions);
		} else {
			return parent::setPermissions($arrayList);
		}
	}
}
