<?php
/**
 * Project
 * Generated by Tyneo Base Tools
 *
 * @package     model
 * @author      Samuel Kauffmann <skauffmann@tyneo.net>
 * @copyright   Copyright (c) 2011, Samuel Kauffmann
 * @link        http://www.tyneo.net
 * @filesource	BaseProjectManager.class.php
 */
namespace model;

/**
 * This class provides an object representation of a Project.
 *
 * @author		Samuel Kauffmann <skauffmann@tyneo.net>
 * @version		1.0
 */
class Project extends Base\BaseProject {

	/**
	 * Set up Project object
	 */
	protected function configure() {

	}
}
