<?php
/**
 * Project
 * Generated by Tyneo Base Tools
 *
 * @package     model
 * @author      Samuel Kauffmann <skauffmann@tyneo.net>
 * @copyright   Copyright (c) 2011, Samuel Kauffmann
 * @link        http://www.tyneo.net
 * @filesource	BaseProjectManager.class.php
 */
namespace model;

/**
 * This class provides manager to manipulate Project objects.
 *
 * @author		Samuel Kauffmann <skauffmann@tyneo.net>
 * @version		1.0
 */
class ProjectManager extends base\BaseProjectManager {
	public function __construct() {
		parent::__construct(\framework\ApplicationContext::getInstance());
	}

}
