<?php
/**
 * Session
 * Generated by Tyneo Base Tools
 *
 * @package     model
 * @author      Samuel Kauffmann <skauffmann@tyneo.net>
 * @copyright   Copyright (c) 2011, Samuel Kauffmann
 * @link        http://www.tyneo.net
 * @filesource	BaseSessionManager.class.php
 */
namespace model;

/**
 * This class provides manager to manipulate Session objects.
 *
 * @author		Samuel Kauffmann <skauffmann@tyneo.net>
 * @version		1.0
 */
class SessionManager extends base\BaseSessionManager {

	public function __construct() {
		parent::__construct(\framework\ApplicationContext::getInstance());
	}
	
	protected function getIdFields() {
		return array('sid', 'hostname');
	}

	public function getCreateQuery(\model\Session $obj) {
		$query = parent::getCreateQuery($obj);
		$query->setField('timestamp', 'NOW()', true);
		return $query;
	}

	public function getUpdateQuery(\model\Session $obj) {
		$query = parent::getUpdateQuery($obj);
		$query->setField('timestamp', 'NOW()', true);
		return $query;
	}

	protected function getObjectFromRow($row) {
		$object = new \model\Session();
		$object->setSid($row->sid);
		$object->setUserId($row->user_id);
		$object->setHostname($row->hostname);
		$object->setTimestamp($row->timestamp);
		$object->setData($row->data);

		$object->setNew(false);
		return $object;
	}
}
