<?php
/**
 * Session
 * Generated by Tyneo Base Tools
 *
 * @package     model
 * @author      Samuel Kauffmann <skauffmann@tyneo.net>
 * @copyright   Copyright (c) 2011, Samuel Kauffmann
 * @link        http://www.tyneo.net
 * @filesource	BaseSessionManager.class.php
 */
namespace model;

/**
 * This class provides an object representation of a Session.
 *
 * @author		Samuel Kauffmann <skauffmann@tyneo.net>
 * @version		1.0
 */
class Session extends Base\BaseSession {

	/**
	 * Set up Session object
	 */
	protected function configure() {

	}
}
