<?php
/**
 * Terms
 * Generated by Tyneo Base Tools
 *
 * @package     model
 * @author      Samuel Kauffmann <skauffmann@tyneo.net>
 * @copyright   Copyright (c) 2011, Samuel Kauffmann
 * @link        http://www.tyneo.net
 * @filesource BaseTermsManager.class.php
 */
namespace model;

/**
 * This class provides an object representation of a Terms.
 *
 * @author  Samuel Kauffmann <skauffmann@tyneo.net>
 * @version  1.0
 */
class Terms extends Base\BaseTerms {

	/**
	 * Set up Terms object
	 */
	protected function configure() {

	}
}
