<?php
/**
 * TermRelationships
 * Generated by Tyneo Base Tools
 *
 * @package     model
 * @author      Samuel Kauffmann <skauffmann@tyneo.net>
 * @copyright   Copyright (c) 2011, Samuel Kauffmann
 * @link        http://www.tyneo.net
 * @filesource BaseTermRelationshipsManager.class.php
 */
namespace model;

/**
 * This class provides manager to manipulate TermRelationships objects.
 *
 * @author  Samuel Kauffmann <skauffmann@tyneo.net>
 * @version  1.0
 */
class TermRelationshipsManager extends base\BaseTermRelationshipsManager {
	public function __construct() {
		parent::__construct(\framework\ApplicationContext::getInstance());
		if($this->context->getConfiguration()->has("wordpress.blog.prefix"))
			$this->setTableName($this->context->getConfiguration()->get("wordpress.blog.prefix", "").$this->getTableName());
	}

}
