<?php
/**
 * TermTaxonomy
 * Generated by Tyneo Base Tools
 *
 * @package     model
 * @author      Samuel Kauffmann <skauffmann@tyneo.net>
 * @copyright   Copyright (c) 2011, Samuel Kauffmann
 * @link        http://www.tyneo.net
 * @filesource BaseTermTaxonomyManager.class.php
 */
namespace model;

/**
 * This class provides an object representation of a TermTaxonomy.
 *
 * @author  Samuel Kauffmann <skauffmann@tyneo.net>
 * @version  1.0
 */
class TermTaxonomy extends Base\BaseTermTaxonomy {

	/**
	 * Set up TermTaxonomy object
	 */
	protected function configure() {

	}
}
