<?php
/**
 * TermRelationships
 * Generated by Tyneo Base Tools
 *
 * @package     model
 * @author      Samuel Kauffmann <skauffmann@tyneo.net>
 * @copyright   Copyright (c) 2011, Samuel Kauffmann
 * @link        http://www.tyneo.net
 * @filesource BaseTermRelationshipsManager.class.php
 */
namespace model;

/**
 * This class provides an object representation of a TermRelationships.
 *
 * @author  Samuel Kauffmann <skauffmann@tyneo.net>
 * @version  1.0
 */
class TermRelationships extends Base\BaseTermRelationships {

	/**
	 * Set up TermRelationships object
	 */
	protected function configure() {

	}
}
