<?php
/**
 * Tool
 * Generated by Tyneo Base Tools
 *
 * @package     model
 * @author      Samuel Kauffmann <skauffmann@tyneo.net>
 * @copyright   Copyright (c) 2011, Samuel Kauffmann
 * @link        http://www.tyneo.net
 * @filesource	BaseToolManager.class.php
 */
namespace model;

/**
 * This class provides an object representation of a Tool.
 *
 * @author		Samuel Kauffmann <skauffmann@tyneo.net>
 * @version		1.0
 */
class Tool extends Base\BaseTool {

	/**
	 * Set up Tool object
	 */
	protected function configure() {

	}
	
	/**
	 * Get the tool type name
	 *
	 * @return the tool type name value
	 */
	public function getToolTypeName() {
		return $this->properties->get('tool_type_name');
	}
	
	/**
	 * Set the tool type name
	 *
	 * @param tool_type_name the tool type name value
	 *
	 * @return BaseTool
	 */
	public function setToolTypeName($tool_type_name) {
		$this->properties->set('tool_type_name', $tool_type_name);
		return $this;
	}
	
	/**
	 * Get the editor name
	 *
	 * @return the editor name value
	 */
	public function getEditorName() {
		return $this->properties->get('editor_name');
	}
	
	/**
	 * Set the editor name
	 *
	 * @param editor_name the editor name value
	 *
	 * @return BaseTool
	 */
	public function setEditorName($editor_name) {
		$this->properties->set('editor_name', $editor_name);
		return $this;
	}
	
	/**
	 * Get the editor description
	 *
	 * @return the editor description value
	 */
	public function getEditorDescription() {
		return $this->properties->get('editor_description');
	}
	
	/**
	 * Set the editor description
	 *
	 * @param editor_description the editor description value
	 *
	 * @return BaseTool
	 */
	public function setEditorDescription($editor_description) {
		$this->properties->set('editor_description', $editor_description);
		return $this;
	}	
	
	/**
	 * Get the editor site
	 *
	 * @return the editor site value
	 */
	public function getEditorSite() {
		return $this->properties->get('editor_site');
	}
	
	/**
	 * Set the editor site
	 *
	 * @param editor_site the editor site value
	 *
	 * @return BaseTool
	 */
	public function setEditorSite($editor_site) {
		$this->properties->set('editor_site', $editor_site);
		return $this;
	}
}
