<?php
/**
 * ToolType
 * Generated by Tyneo Base Tools
 *
 * @package     model
 * @author      Samuel Kauffmann <skauffmann@tyneo.net>
 * @copyright   Copyright (c) 2011, Samuel Kauffmann
 * @link        http://www.tyneo.net
 * @filesource	BaseToolTypeManager.class.php
 */
namespace model;

/**
 * This class provides an object representation of a ToolType.
 *
 * @author		Samuel Kauffmann <skauffmann@tyneo.net>
 * @version		1.0
 */
class ToolType extends Base\BaseToolType {

	/**
	 * Set up ToolType object
	 */
	protected function configure() {

	}
}
