<?php
/**
 * Training
 * Generated by Tyneo Base Tools
 *
 * @package     model
 * @author      Samuel Kauffmann <skauffmann@tyneo.net>
 * @copyright   Copyright (c) 2011, Samuel Kauffmann
 * @link        http://www.tyneo.net
 * @filesource	BaseTrainingManager.class.php
 */
namespace model;

/**
 * This class provides an object representation of a Training.
 *
 * @author		Samuel Kauffmann <skauffmann@tyneo.net>
 * @version		1.0
 */
class Training extends Base\BaseTraining {

	/**
	 * Set up Training object
	 */
	protected function configure() {

	}
}
