<?php
/**
 * Usermeta
 * Generated by Tyneo Base Tools
 *
 * @package     model
 * @author      Samuel Kauffmann <skauffmann@tyneo.net>
 * @copyright   Copyright (c) 2011, Samuel Kauffmann
 * @link        http://www.tyneo.net
 * @filesource BaseUsermetaManager.class.php
 */
namespace model;

/**
 * This class provides an object representation of a Usermeta.
 *
 * @author  Samuel Kauffmann <skauffmann@tyneo.net>
 * @version  1.0
 */
class Usermeta extends Base\BaseUsermeta {

	/**
	 * Set up Usermeta object
	 */
	protected function configure() {

	}
}
