<?php
/**
 * Users
 * Generated by Tyneo Base Tools
 *
 * @package     model
 * @author      Samuel Kauffmann <skauffmann@tyneo.net>
 * @copyright   Copyright (c) 2011, Samuel Kauffmann
 * @link        http://www.tyneo.net
 * @filesource BaseUsersManager.class.php
 */
namespace model;

/**
 * This class provides an object representation of a Users.
 *
 * @author  Samuel Kauffmann <skauffmann@tyneo.net>
 * @version  1.0
 */
class Users extends Base\BaseUsers {

	/**
	 * Set up Users object
	 */
	protected function configure() {

	}
}
