<?php
/**
 * UserProfile
 * Generated by Tyneo Base Tools
 *
 * @package     model
 * @author      Samuel Kauffmann <skauffmann@tyneo.net>
 * @copyright   Copyright (c) 2011, Samuel Kauffmann
 * @link        http://www.tyneo.net
 * @filesource	BaseUserProfileManager.class.php
 */
namespace model;

/**
 * This class provides an object representation of a UserProfile.
 *
 * @author		Samuel Kauffmann <skauffmann@tyneo.net>
 * @version		1.0
 */
class UserProfile extends Base\BaseUserProfile {

	/**
	 * Set up UserProfile object
	 */
	protected function configure() {

	}
}
