<?php
/**
 * WpkbPostmeta
 * Generated by Tyneo Base Tools
 *
 * @package     model
 * @author      Samuel Kauffmann <skauffmann@tyneo.net>
 * @copyright   Copyright (c) 2011, Samuel Kauffmann
 * @link        http://www.tyneo.net
 * @filesource	BaseWpkbPostmetaManager.class.php
 */
namespace model;

/**
 * This class provides an object representation of a WpkbPostmeta.
 *
 * @author		Samuel Kauffmann <skauffmann@tyneo.net>
 * @version		1.0
 */
class WpkbPostmeta extends Base\BaseWpkbPostmeta {

	/**
	 * Set up WpkbPostmeta object
	 */
	protected function configure() {

	}
}
