<?php
/**
 * WpkbPosts
 * Generated by Tyneo Base Tools
 *
 * @package     model
 * @author      Samuel Kauffmann <skauffmann@tyneo.net>
 * @copyright   Copyright (c) 2011, Samuel Kauffmann
 * @link        http://www.tyneo.net
 * @filesource	BaseWpkbPostsManager.class.php
 */
namespace model;

/**
 * This class provides an object representation of a WpkbPosts.
 *
 * @author		Samuel Kauffmann <skauffmann@tyneo.net>
 * @version		1.0
 */
class WpkbPosts extends Base\BaseWpkbPosts {

	/**
	 * Set up WpkbPosts object
	 */
	protected function configure() {

	}
}
