<?php
/**
 * WpkbComments
 * Generated by Tyneo Base Tools
 *
 * @package     model
 * @author      Samuel Kauffmann <skauffmann@tyneo.net>
 * @copyright   Copyright (c) 2011, Samuel Kauffmann
 * @link        http://www.tyneo.net
 * @filesource	BaseWpkbCommentsManager.class.php
 */
namespace model;

/**
 * This class provides an object representation of a WpkbComments.
 *
 * @author		Samuel Kauffmann <skauffmann@tyneo.net>
 * @version		1.0
 */
class WpkbComments extends Base\BaseWpkbComments {

	/**
	 * Set up WpkbComments object
	 */
	protected function configure() {

	}
}
