<?php
/**
 * WpkbTermTaxonomy
 * Generated by Tyneo Base Tools
 *
 * @package     model
 * @author      Samuel Kauffmann <skauffmann@tyneo.net>
 * @copyright   Copyright (c) 2011, Samuel Kauffmann
 * @link        http://www.tyneo.net
 * @filesource	BaseWpkbTermTaxonomyManager.class.php
 */
namespace model;

/**
 * This class provides an object representation of a WpkbTermTaxonomy.
 *
 * @author		Samuel Kauffmann <skauffmann@tyneo.net>
 * @version		1.0
 */
class WpkbTermTaxonomy extends Base\BaseWpkbTermTaxonomy {

	/**
	 * Set up WpkbTermTaxonomy object
	 */
	protected function configure() {

	}
}
