<?php
/**
 * WpkbOptions
 * Generated by Tyneo Base Tools
 *
 * @package     model
 * @author      Samuel Kauffmann <skauffmann@tyneo.net>
 * @copyright   Copyright (c) 2011, Samuel Kauffmann
 * @link        http://www.tyneo.net
 * @filesource	BaseWpkbOptionsManager.class.php
 */
namespace model;

/**
 * This class provides an object representation of a WpkbOptions.
 *
 * @author		Samuel Kauffmann <skauffmann@tyneo.net>
 * @version		1.0
 */
class WpkbOptions extends Base\BaseWpkbOptions {

	/**
	 * Set up WpkbOptions object
	 */
	protected function configure() {

	}
}
