<?php
/**
 * WpkbCommentmeta
 * Generated by Tyneo Base Tools
 *
 * @package     model
 * @author      Samuel Kauffmann <skauffmann@tyneo.net>
 * @copyright   Copyright (c) 2011, Samuel Kauffmann
 * @link        http://www.tyneo.net
 * @filesource	BaseWpkbCommentmetaManager.class.php
 */
namespace model;

/**
 * This class provides an object representation of a WpkbCommentmeta.
 *
 * @author		Samuel Kauffmann <skauffmann@tyneo.net>
 * @version		1.0
 */
class WpkbCommentmeta extends Base\BaseWpkbCommentmeta {

	/**
	 * Set up WpkbCommentmeta object
	 */
	protected function configure() {

	}
}
