<?php
/**
 * WpkbUsermeta
 * Generated by Tyneo Base Tools
 *
 * @package     model
 * @author      Samuel Kauffmann <skauffmann@tyneo.net>
 * @copyright   Copyright (c) 2011, Samuel Kauffmann
 * @link        http://www.tyneo.net
 * @filesource	BaseWpkbUsermetaManager.class.php
 */
namespace model;

/**
 * This class provides an object representation of a WpkbUsermeta.
 *
 * @author		Samuel Kauffmann <skauffmann@tyneo.net>
 * @version		1.0
 */
class WpkbUsermeta extends Base\BaseWpkbUsermeta {

	/**
	 * Set up WpkbUsermeta object
	 */
	protected function configure() {

	}
}
