<?php
/**
 * WpkbTerms
 * Generated by Tyneo Base Tools
 *
 * @package     model
 * @author      Samuel Kauffmann <skauffmann@tyneo.net>
 * @copyright   Copyright (c) 2011, Samuel Kauffmann
 * @link        http://www.tyneo.net
 * @filesource	BaseWpkbTermsManager.class.php
 */
namespace model;

/**
 * This class provides an object representation of a WpkbTerms.
 *
 * @author		Samuel Kauffmann <skauffmann@tyneo.net>
 * @version		1.0
 */
class WpkbTerms extends Base\BaseWpkbTerms {

	/**
	 * Set up WpkbTerms object
	 */
	protected function configure() {

	}
}
