<?php
/**
 * WpkbLinks
 * Generated by Tyneo Base Tools
 *
 * @package     model
 * @author      Samuel Kauffmann <skauffmann@tyneo.net>
 * @copyright   Copyright (c) 2011, Samuel Kauffmann
 * @link        http://www.tyneo.net
 * @filesource	BaseWpkbLinksManager.class.php
 */
namespace model;

/**
 * This class provides an object representation of a WpkbLinks.
 *
 * @author		Samuel Kauffmann <skauffmann@tyneo.net>
 * @version		1.0
 */
class WpkbLinks extends Base\BaseWpkbLinks {

	/**
	 * Set up WpkbLinks object
	 */
	protected function configure() {

	}
}
