<?php
/**
 * WpkbTermRelationships
 * Generated by Tyneo Base Tools
 *
 * @package     model
 * @author      Samuel Kauffmann <skauffmann@tyneo.net>
 * @copyright   Copyright (c) 2011, Samuel Kauffmann
 * @link        http://www.tyneo.net
 * @filesource	BaseWpkbTermRelationshipsManager.class.php
 */
namespace model;

/**
 * This class provides an object representation of a WpkbTermRelationships.
 *
 * @author		Samuel Kauffmann <skauffmann@tyneo.net>
 * @version		1.0
 */
class WpkbTermRelationships extends Base\BaseWpkbTermRelationships {

	/**
	 * Set up WpkbTermRelationships object
	 */
	protected function configure() {

	}
}
