<?php
/**
 * WpkbUsers
 * Generated by Tyneo Base Tools
 *
 * @package     model
 * @author      Samuel Kauffmann <skauffmann@tyneo.net>
 * @copyright   Copyright (c) 2011, Samuel Kauffmann
 * @link        http://www.tyneo.net
 * @filesource	BaseWpkbUsersManager.class.php
 */
namespace model;

/**
 * This class provides an object representation of a WpkbUsers.
 *
 * @author		Samuel Kauffmann <skauffmann@tyneo.net>
 * @version		1.0
 */
class WpkbUsers extends Base\BaseWpkbUsers {

	/**
	 * Set up WpkbUsers object
	 */
	protected function configure() {

	}
}
