<?php
/**
 * WpPosts
 * Generated by Tyneo Base Tools
 *
 * @package     model
 * @author      Samuel Kauffmann <skauffmann@tyneo.net>
 * @copyright   Copyright (c) 2011, Samuel Kauffmann
 * @link        http://www.tyneo.net
 * @filesource	BaseWpPostsManager.class.php
 */
namespace model;

/**
 * This class provides an object representation of a WpPosts.
 *
 * @author		Samuel Kauffmann <skauffmann@tyneo.net>
 * @version		1.0
 */
class WpPosts extends Base\BaseWpPosts {

	/**
	 * Set up WpPosts object
	 */
	protected function configure() {

	}
}
