homepage:
  url:  /
  param: { module: redirection, action: forward, next: welcome }
  requirements: { device_type: desktop }

homepage_mobile:
  url:  /
  param: { module: redirection, action: forward, next: welcome_mobile }
  requirements: { device_type: mobile }


default:
  url: _page_en_erreur_
  param: { module: redirection, action: redirect, next: "http://www.tyneo.dev/404.html" }