all:
  guest_user:             anonymous
  reserved_users:         (admin|root|administrator)

  mail_server:            smtp.free.fr
  mail_from:              contact@tyneo.net
  mail_replyto:           contact@tyneo.net
  
  default_alt:            html
  catch_error:            true
  
  file_storage_dir:       /files