statistics:
  - name: Globale
    percent: 100
    color: "#74941F"
  - name: Progression du stage
    percent: 98
    color: "#74941F"
  - name: Méthodes pédagogiques
    percent: 99
    color: "#BC006E"
  - name: Supports & documentations
    percent: 99
    color: "#BC006E"

categories:
  Planisware: blue
  Caliber: green

modules:
  - name: Débuter avec Planisware
    ref: "#FRMPLW-001"
    duration: 1 jour
    practice: 45
    strong: 10
    price: "970€"
    tag: Planisware
    file: fr/training/planisware_getting_started.html
    learn: "Ce programme de formation a été spécialement élaboré afin de fournir une vue d'ensemble de Planisware. Si vous ne connaissez pas encore Planisware, ce module est idéal. Vous découvrirez le fonctionnement global de l'application, le b.a.-ba pour bien débuter avec Planisware et plus particulièrement les modules « Projets » et « Portefeuille » de Planisware, ainsi qu'une vue d'ensemble des différents modules."
    requirements: "Ce module convient aux personnes ayant peu ou pas d'expérience sur Planisware. Une connaissance de l'environnement Windows et de la navigation Internet est requise."
    for_who: "Tout utilisateur ou futur utilisateur de Planisware."
    about_trainers: "Votre formateur est également consultant sur des projets d'intégration Planisware. En mêlant ses compétences métier et produit, il pourra vous faire bénéficier de son expertise et ses conseils avec des cas concrets."
    program:
      - name: Introduction à Planisware
        detail:
          - Définitions et terminologie
          - Introduction à l'outil Planisware
          - Présentation de la méthode Stage-Gate
      - name: Prise en main de Planisware
        detail:
          - Premiers pas avec Planisware
          - Concept des styles
      - name: Gérer un projet avec Planisware
        detail:
          - Démarrer un projet
          - Saisir les activités du projet (WBS)
          - Allouer des ressources et déclarer des dépenses
          - Créer une référence budgétaire
          - Mettre à jour son projet
          - Communiquer sur son projet (rapports et présentations)
          - Clôturer son projet
      - name: Suivre un portefeuille de projets
        detail:
          - Constituer son portefeuille projets
          - Utiliser les feuilles de route
          - Réaliser des tableaux de bord avec Planisware Explorer
      - name: Autres modules de l'application
        detail:
          - Gérer un projet Agile avec Planisware
          - Gestion des idées
          - Echange de livrables
      - name: Plus loin avec Planisware
        detail:
          - Les interfaces Planisware
          - Les possibilités de paramétrage
  - name: Gérer son projet avec Planisware
    ref: "#FRMPLW-002"
    price: "970€"
    duration: 1 jour
    practice: 50
    strong: 30
    tag: Planisware
    file: fr/training/planisware_mod_pm.html
    learn: "A la fin de ce module vous saurez créer et manipuler vos premiers projets dans Planisware. Le programme abordé vous permettra de vous remémorer des bases de la gestion de projet et leur application dans l’outil. Cette formation mélange habillement la théorie et la pratique de l’outil Planisware afin de permettre au stagiaire d’appréhender plus facilement les rudiments de l’outil."
    requirements: "Ce module convient aux personnes ayant peu ou pas d'expérience sur Planisware. Une connaissance de l'environnement Windows et de la navigation Internet est requise."
    for_who: "Tout utilisateur ou futur utilisateur de Planisware."
    about_trainers: "Votre formateur est également consultant sur des projets d'intégration Planisware. En mêlant ses compétences métier et produit, il pourra vous faire bénéficier de son expertise et ses conseils avec des cas concrets."
    program:
      - name: Introduction à la gestion de projet
        detail:
          - Définitions et terminologie
          - Les acteurs
          - Le cycle de vie d’un projet
      - name: Découverte de Planisware
        detail:
          - "Planisware : solution de gestion de projets (EPM) et de portefeuille de projets (PPM)"
          - Positionnement de Planisware sur le marché
          - Les différents modules fonctionnels
          - La méthode stage and gate
          - Architecture de l’outil
          - Premiers pas avec l’outil
      - name: Gérer un projet avec Planisware
        detail:
          - Initier un projet et définir ses propriétés
          - Saisir les activités du projet (WBS)
          - Définir des dépendances (liens) et contraintes
          - Allouer des ressources (RBS) et déclarer des dépenses
          - Créer une référence budgétaire
          - Mettre à jour son projet
          - Suivre et communiquer sur son projet
          - Clôturer son projet
      - name: Suivre un portefeuille de projets
        detail:
          - Constituer son portefeuille projets
          - Suivre son portefeuille de projets
  - name: Configurer et administrer Planisware
    ref: "#FRMPLW-003"
    price: "1 500€"
    practice: 65
    duration: 2 jours
    strong: 50
    tag: Planisware
    file: fr/training/planisware_admin.html
    learn: "Ce module a été conçu afin de permettre au stagiaire d’acquérir et de maitriser les opérations essentielles à la configuration et l’administration du logiciel d’entreprise Planisware."
    requirements: "Avoir suivi la formation « Gérer son projet avec Planisware » ou connaitre les bases de la gestion de projet dans Planisware."
    for_who: "Futur administrateur ou intégrateur Planisware. Cette formation peut aussi être un plus pour les utilisateurs référents."
    about_trainers: "Votre formateur est également consultant sur des projets d'intégration Planisware. En mêlant ses compétences métier et produit, il pourra vous faire bénéficier de son expertise et ses conseils avec des cas concrets."
    program:
      - name: Découverte de Planisware Pro
        detail:
          - Premiers pas avec Planisware Pro
          - "Les 4 modes de travail: Mode planning / Conception / Rapport / Processes"
          - Le mode Administrateur
      - name: Le concept des fichiers dans Planisware
        detail:
          - Fichiers d’environnements
          - Fichiers communs
          - Fichiers Projets
      - name: Introduction à Planisware Processes
      - name: Le référentiel commun
        detail:
          - Groupes et utilisateurs
          - "Couts : Lignes de cout (CBS), unité d’œuvre"
          - Responsable (OBS), Ressources (RBS) et calendriers
          - Types d’activités
      - name: Les paramètres Processes
        detail:
          - Activation des modules
          - Valeurs par défaut
          - Organisation des menus
      - name: Initiation à Planisware Authors
        detail:
          - Créer et partager des styles
          - Concevoir des formules
          - Utiliser les macros et les actions multiples
      - name: Administration de l’outil Planisware
        detail:
          - Installer des clés de licence
          - Démarrer et arrêter les services Planisware
          - Le watchdog et le site d’administration
          - Les journaux applicatifs
          - Sauvegarder / restaurer la base Planisware
          - Sauvegarder / restaurer un fichier
      - name: Bonnes pratiques
        detail:
          - Gestion des journaux
          - Scripts de maintenance
          - Opérations manuelles
  - name: Paramétrer Planisware
    ref: "#FRMPLW-004"
    price: "1 700€"
    practice: 65
    duration: 2 jours
    strong: 80
    tag: Planisware
    file: fr/training/planisware_integrator.html
    learn: "Etape indispensable pour mettre en œuvre la solution Planisware au sein d’une organisation, ce module permet d’appréhender l’essentiel des possibilités de paramétrage et de personnalisation de l’application Planisware."
    requirements: "Avoir suivi la formation « Configurer et administrer Planisware » ou maitriser les principes abordés."
    for_who: "Responsable de l’application Planisware, administrateur avancé ou intégrateur Planisware."
    about_trainers: "Votre formateur est également consultant sur des projets d'intégration Planisware. En mêlant ses compétences métier et produit, il pourra vous faire bénéficier de son expertise et ses conseils avec des cas concrets."
    program:
      - name: Méthodologie de développement avec Planisware
        detail:
          - Bonnes pratiques Planisware
          - Objets (LSP) et environnements (DPE)
          - Remplacer des fonctionnalités existantes
          - Délivrer ses développements
      - name: Les ensembles de paramètres
        detail:
          - Paramétrage des codes, formats et libellés
          - Définition des valeurs par défaut
          - Définition des ordonnancements, couleurs et polices par défaut
      - name: Les attributs calculés
        detail:
          - Formules nommées
          - Champs symboliques
      - name: Le model de données Planisware
        detail:
          - Présentation du model de données standard
          - Ajouter de nouveaux champs et types d’attributs
          - Créer de nouvelles tables (stockées, temporaires)
          - Gérer des attributs de relations
          - Définir de nouvelles arborescences
      - name: Concevoir des écrans et rapports Planisware
      - name: Les évènements (alertes / verrous)
      - name: Les coûts
        detail:
          - Les courbes composites
          - Les champs coûts
          - Les tables de coûts
      - name: Autres objets de personnalisation
        detail:
          - Les clés textes / internationalisation
          - Les references templates
      - name: Plus loin avec Planisware
        detail:
          - Les traitements asynchrones (Batchs intranet/ systèmes)
          - Le langage de script Planisware (OJS)
          - Les interfaces avec les outils tiers
  - name: Maîtriser le langage script Planisware
    ref: "#FRMPLW-005"
    price: "1 140€"
    practice: 75
    duration: 1 jour
    strong: 90
    tag: Planisware
    file: fr/training/planisware_learn_ojs.html
    learn: "Planisware propose en plus des méthodes traditionnelles pour personnaliser son produit (formules, paramètres, etc...) un langage de programmation interprété et basé sur un moteur JavaScript. Cette formation proposée par Tyneo Consulting va vous permettre de maîtriser les différents concepts de ce langage afin de développer vos propres scripts."
    requirements: "Maîtrise des conceptes généraux du paramétrage de l'outil Planisware."
    for_who: "Cette formation s'adresse principalement aux intégrateurs Planisware et personnes souhaitant savoir lire, comprendre et créer des scripts OJS."
    about_trainers: "Votre formateur est également consultant sur des projets d'intégration Planisware. En mêlant ses compétences métier et produit, il pourra vous faire bénéficier de son expertise et ses conseils avec des cas concrets."
    program:
      - name: Découverte des bases du langage JavaScript
        detail:
          - Déclaration et portée des variables
          - Typage des données
          - Opérateurs logiques et arithmétiques. Boucles (for, while...)
          - Création de fonctions et procédures
      - name: Spécificités du langage script Planisware / OJS
        detail:
          - Méthodologie de développement
          - Outils de développement
          - Opérateurs additionnels (for)
          - Fonctions de base (collections, macros, formules...)
          - Gestion des erreurs et des exceptions
      - name: Manipulation des objets Planisware
        detail:
          - Tables et classes Planisware
          - Formules et macros
          - Dépenses et ressources
          - Champs couts, courbes
      - name: Programmation orientée objets
        detail:
          - Création et utilisation des classes
          - Création de méthodes
      - name: Formulaires et scripts Opx2
        detail:
          - Intégration de scripts dans les formulaires
          - Modification du formulaire et des objets du formulaire
          - Validation par script
      - name: Intéraction avec les objets graphiques
        detail:
          - Dessiner en OJS
          - Modifier une vue Gantt
      - name: Exécution asynchrone des scripts
        detail:
          - Batch système (crontab, tâche planifiée)
          - Batch Intranet
          - Traitement en arrière plan
      - name: Bibliothèques avancées
        detail:
          - Amélioration des classes de base (String, OpxProject, etc...)
          - Bibliothèque Utility*
          - Journal des évènements (Logger)
      - name: Programmation avancée
        detail:
          - Trigger (daemons et fonctions Wrapper)
          - Introspection des objets
          - Lisp et Planisware
  - name: Caliber et la gestion des exigences
    ref: "#FRMCAL-001"
    practice: 55
    duration: 3 jours
    strong: 25
    tag: Caliber
    file: fr/training/caliber_requirement_management.html
    learn: >
      <div class="table-list"><ul>
      <li>Créer et manipuler des exigences textuelles (Author) et visuelles (Visualize)</li>
      <li>Gérer des périmètres d'exigences dans Caliber</li>
      <li>Réaliser et exploiter la traçabilité entre les exigences ou avec les tests</li>
      <li>Relire des exigences et émettre des remarques</li>
      <li>Extraire les exigences sous forme de rapport ou dans un document Word</li>
      <li>Exploiter les fonctionnalités de productivité de Caliber</li>
      </ul></div>
    requirements: "Aucun pré-requis n'est nécessaire pour participer à cette formation."
    for_who: >
      <div class="table-list"><ul>
      <li>Rédacteurs d'exigences ou de spécifications</li>
      <li>Relecteurs et validateurs</li>
      <li>Administrateurs fonctionnelles de l'outil</li>
      <li>Ingénieurs Qualité / Performance</li>
      </ul></div>
    about_trainers: "Outre son expertise outil, votre formateur dispose d’une réelle expérience dans l’ingénierie des exigences. Il intervient régulièrement sur des projets en tant qu’analyste système/logiciel et est certifié IREB CPRE-FL (Ingénierie des Exigences)."
    program:
      - name: Principes de la gestion des exigences
      - name: Caliber et les exigences
      - name: Premiers pas avec l'outil
      - name: Acquisition des exigences
      - name: Collaboration autour des exigences
      - name: Gestion des périmètres
      - name: Traçabilité verticale
      - name: Travailler au quotidien avec Caliber
      - name: Interfaces et intégration tiers
  - name: Administration de l'outil Caliber
    ref: "#FRMCAL-002"
    practice: 65
    duration: 1 jour
    strong: 80
    tag: Caliber
    file: fr/training/caliber_administrator.html
    learn: >
      <div class="table-list"><ul>
      <li>Connaitre l'architecture de Caliber</li>
      <li>Administrer le référentiel Caliber</li>
      <li>Paramétrer et personnaliser les projets et l'application</li>
      </ul></div>
    requirements: "Bien que ceci ne soit pas un pré-requis indispensable, il est préférable disposer d'un minimum de connaissances techniques en informatique."
    for_who: >
      <div class="table-list"><ul>
      <li>Administrateurs de Caliber</li>
      <li>Equipes de support outil</li>
      </ul></div>
    about_trainers: "Outre son expertise outil, votre formateur dispose d’une réelle expérience dans l’ingénierie des exigences. Il intervient régulièrement sur des projets en tant qu’analyste système/logiciel et est certifié IREB CPRE-FL (Ingénierie des Exigences)."
    program:
      - name: Introduction à Caliber et son administration
        detail:
          - Architecture Caliber
          - Définitions et terminologie
          - Premiers pas avec Caliber Administrator
      - name: Gestion des utilisateurs
        detail:
          - Créer un utilisateur Caliber
          - Gérer des groupes d’utilisateurs
      - name: Gestion des projets
        detail:
          - Créer un projet
          - Définir les types d’exigences
          - Configurer les droits d’accès
      - name: Personnalisation de Caliber
        detail:
          - Ajouter de nouveau type d’exigences
          - Modifier les attributs existants
          - Créer ses propres attributs
          - Améliorer l’interface Caliber
      - name: Construction des modèles de document Docfactory
        detail:
          - Concepts du docfactory
          - Grammaire et syntaxte du docfactory
          - Premiers modèles de documents
      - name: Administration du serveur applicatif
        detail:
          - Installer des clés de licence
          - Paramétrer les notifications mails
          - Démarrer et arrêter les services
          - Les journaux applicatifs
          - Exporter / importer des données
          - Sauvegarder / restaurer une base
      - name: Intégration avec des outils tiers
        detail:
          - Caliber dans les autres outils
          - Tracabilité externe (outils tiers)
          - Caliber et les outils décisionnels
      - name: Etendre les fonctionnalités de Caliber
        detail:
          - Introduction aux API Caliber
          - Intégration dans l’environnmenent Caliber
          - Exemples
