<?php
/**
 * BaseAccounting
 * Generated by Tyneo Base Tools
 *
 * @package     model
 * @author      Samuel Kauffmann <skauffmann@tyneo.net>
 * @copyright   Copyright (c) 2011, Samuel Kauffmann
 * @link        http://www.tyneo.net
 * @filesource	BaseAccounting.class.php
 */
namespace model\base;

/**
 * This class provides an object representation of a Accounting.
 *
 * @author		Samuel Kauffmann <skauffmann@tyneo.net>
 * @version		1.0
 */
abstract class BaseAccounting extends AbstractBaseObject {


	/**
	 * Get the id
	 *
	 * @return id the id value
	 */
	public function getId() {
		return $this->properties->get('id');
	}

	/**
	 * Set the id
	 *
	 * @param id the id value
	 *
	 * @return BaseAccounting
	 */
	public function setId($id) {
		$this->properties->set('id', $id);
		return $this;
	}


	/**
	 * Get the name
	 *
	 * @return name the name value
	 */
	public function getName() {
		return $this->properties->get('name');
	}

	/**
	 * Set the name
	 *
	 * @param name the name value
	 *
	 * @return BaseAccounting
	 */
	public function setName($name) {
		$this->properties->set('name', $name);
		return $this;
	}


	/**
	 * Get the description
	 *
	 * @return description the description value
	 */
	public function getDescription() {
		return $this->properties->get('description');
	}

	/**
	 * Set the description
	 *
	 * @param description the description value
	 *
	 * @return BaseAccounting
	 */
	public function setDescription($description) {
		$this->properties->set('description', $description);
		return $this;
	}


	/**
	 * Get the date
	 *
	 * @return date the date value
	 */
	public function getDate() {
		return $this->properties->get('date');
	}

	/**
	 * Set the date
	 *
	 * @param date the date value
	 *
	 * @return BaseAccounting
	 */
	public function setDate($date) {
		$this->properties->set('date', $date);
		return $this;
	}


	/**
	 * Get the amount
	 *
	 * @return amount the amount value
	 */
	public function getAmount() {
		return $this->properties->get('amount');
	}

	/**
	 * Set the amount
	 *
	 * @param amount the amount value
	 *
	 * @return BaseAccounting
	 */
	public function setAmount($amount) {
		$this->properties->set('amount', $amount);
		return $this;
	}


	/**
	 * Get the vat
	 *
	 * @return vat the vat value
	 */
	public function getVat() {
		return $this->properties->get('vat');
	}

	/**
	 * Set the vat
	 *
	 * @param vat the vat value
	 *
	 * @return BaseAccounting
	 */
	public function setVat($vat) {
		$this->properties->set('vat', $vat);
		return $this;
	}


	/**
	 * Get the is_chargeable
	 *
	 * @return is_chargeable the is_chargeable value
	 */
	public function getIsChargeable() {
		return $this->properties->get('is_chargeable');
	}

	/**
	 * Set the is_chargeable
	 *
	 * @param is_chargeable the is_chargeable value
	 *
	 * @return BaseAccounting
	 */
	public function setIsChargeable($is_chargeable) {
		$this->properties->set('is_chargeable', $is_chargeable);
		return $this;
	}


	/**
	 * Get the nature
	 *
	 * @return nature the nature value
	 */
	public function getNature() {
		return $this->properties->get('nature');
	}

	/**
	 * Set the nature
	 *
	 * @param nature the nature value
	 *
	 * @return BaseAccounting
	 */
	public function setNature($nature) {
		$this->properties->set('nature', $nature);
		return $this;
	}


	/**
	 * Get the account_id
	 *
	 * @return account_id the account_id value
	 */
	public function getAccountId() {
		return $this->properties->get('account_id');
	}

	/**
	 * Set the account_id
	 *
	 * @param account_id the account_id value
	 *
	 * @return BaseAccounting
	 */
	public function setAccountId($account_id) {
		$this->properties->set('account_id', $account_id);
		return $this;
	}


	/**
	 * Get the project_id
	 *
	 * @return project_id the project_id value
	 */
	public function getProjectId() {
		return $this->properties->get('project_id');
	}

	/**
	 * Set the project_id
	 *
	 * @param project_id the project_id value
	 *
	 * @return BaseAccounting
	 */
	public function setProjectId($project_id) {
		$this->properties->set('project_id', $project_id);
		return $this;
	}


	public function __toString() {
				return $this->getName();
    }



	public function getAccount() {
		$accountManager = new \model\AccountManager();
		return $accountManager->getAccount($this->getAccountId());
	}

	public function getProject() {
		$projectManager = new \model\ProjectManager();
		return $projectManager->getProject($this->getProjectId());
	}

}
