<?php
/**
 * BaseAccount
 * Generated by Tyneo Base Tools
 *
 * @package     model
 * @author      Samuel Kauffmann <skauffmann@tyneo.net>
 * @copyright   Copyright (c) 2011, Samuel Kauffmann
 * @link        http://www.tyneo.net
 * @filesource	BaseAccount.class.php
 */
namespace model\base;

/**
 * This class provides an object representation of a Account.
 *
 * @author		Samuel Kauffmann <skauffmann@tyneo.net>
 * @version		1.0
 */
abstract class BaseAccount extends AbstractBaseObject {


	/**
	 * Get the id
	 *
	 * @return id the id value
	 */
	public function getId() {
		return $this->properties->get('id');
	}

	/**
	 * Set the id
	 *
	 * @param id the id value
	 *
	 * @return BaseAccount
	 */
	public function setId($id) {
		$this->properties->set('id', $id);
		return $this;
	}


	/**
	 * Get the ref
	 *
	 * @return ref the ref value
	 */
	public function getRef() {
		return $this->properties->get('ref');
	}

	/**
	 * Set the ref
	 *
	 * @param ref the ref value
	 *
	 * @return BaseAccount
	 */
	public function setRef($ref) {
		$this->properties->set('ref', $ref);
		return $this;
	}


	/**
	 * Get the name
	 *
	 * @return name the name value
	 */
	public function getName() {
		return $this->properties->get('name');
	}

	/**
	 * Set the name
	 *
	 * @param name the name value
	 *
	 * @return BaseAccount
	 */
	public function setName($name) {
		$this->properties->set('name', $name);
		return $this;
	}


	/**
	 * Get the description
	 *
	 * @return description the description value
	 */
	public function getDescription() {
		return $this->properties->get('description');
	}

	/**
	 * Set the description
	 *
	 * @param description the description value
	 *
	 * @return BaseAccount
	 */
	public function setDescription($description) {
		$this->properties->set('description', $description);
		return $this;
	}


	/**
	 * Get the parent
	 *
	 * @return parent the parent value
	 */
	public function getParent() {
		return $this->properties->get('parent');
	}

	/**
	 * Set the parent
	 *
	 * @param parent the parent value
	 *
	 * @return BaseAccount
	 */
	public function setParent($parent) {
		$this->properties->set('parent', $parent);
		return $this;
	}


	public function __toString() {
				return $this->getName();
    }



}
