<?php
/**
 * BaseTraining
 * Generated by Tyneo Base Tools
 *
 * @package     model
 * @author      Samuel Kauffmann <skauffmann@tyneo.net>
 * @copyright   Copyright (c) 2011, Samuel Kauffmann
 * @link        http://www.tyneo.net
 * @filesource	BaseTraining.class.php
 */
namespace model\base;

/**
 * This class provides an object representation of a Training.
 *
 * @author		Samuel Kauffmann <skauffmann@tyneo.net>
 * @version		1.0
 */
abstract class BaseTraining extends AbstractBaseObject {


	/**
	 * Get the id
	 *
	 * @return id the id value
	 */
	public function getId() {
		return $this->properties->get('id');
	}

	/**
	 * Set the id
	 *
	 * @param id the id value
	 *
	 * @return BaseTraining
	 */
	public function setId($id) {
		$this->properties->set('id', $id);
		return $this;
	}


	/**
	 * Get the slug
	 *
	 * @return slug the slug value
	 */
	public function getSlug() {
		return $this->properties->get('slug');
	}

	/**
	 * Set the slug
	 *
	 * @param slug the slug value
	 *
	 * @return BaseTraining
	 */
	public function setSlug($slug) {
		$this->properties->set('slug', $slug);
		return $this;
	}


	/**
	 * Get the name
	 *
	 * @return name the name value
	 */
	public function getName() {
		return $this->properties->get('name');
	}

	/**
	 * Set the name
	 *
	 * @param name the name value
	 *
	 * @return BaseTraining
	 */
	public function setName($name) {
		$this->properties->set('name', $name);
		return $this;
	}


	/**
	 * Get the category
	 *
	 * @return category the category value
	 */
	public function getCategory() {
		return $this->properties->get('category');
	}

	/**
	 * Set the category
	 *
	 * @param category the category value
	 *
	 * @return BaseTraining
	 */
	public function setCategory($category) {
		$this->properties->set('category', $category);
		return $this;
	}


	/**
	 * Get the objective
	 *
	 * @return objective the objective value
	 */
	public function getObjective() {
		return $this->properties->get('objective');
	}

	/**
	 * Set the objective
	 *
	 * @param objective the objective value
	 *
	 * @return BaseTraining
	 */
	public function setObjective($objective) {
		$this->properties->set('objective', $objective);
		return $this;
	}


	/**
	 * Get the requirements
	 *
	 * @return requirements the requirements value
	 */
	public function getRequirements() {
		return $this->properties->get('requirements');
	}

	/**
	 * Set the requirements
	 *
	 * @param requirements the requirements value
	 *
	 * @return BaseTraining
	 */
	public function setRequirements($requirements) {
		$this->properties->set('requirements', $requirements);
		return $this;
	}


	/**
	 * Get the recipient
	 *
	 * @return recipient the recipient value
	 */
	public function getRecipient() {
		return $this->properties->get('recipient');
	}

	/**
	 * Set the recipient
	 *
	 * @param recipient the recipient value
	 *
	 * @return BaseTraining
	 */
	public function setRecipient($recipient) {
		$this->properties->set('recipient', $recipient);
		return $this;
	}


	/**
	 * Get the agenda
	 *
	 * @return agenda the agenda value
	 */
	public function getAgenda() {
		return $this->properties->get('agenda');
	}

	/**
	 * Set the agenda
	 *
	 * @param agenda the agenda value
	 *
	 * @return BaseTraining
	 */
	public function setAgenda($agenda) {
		$this->properties->set('agenda', $agenda);
		return $this;
	}


	/**
	 * Get the duration
	 *
	 * @return duration the duration value
	 */
	public function getDuration() {
		return $this->properties->get('duration');
	}

	/**
	 * Set the duration
	 *
	 * @param duration the duration value
	 *
	 * @return BaseTraining
	 */
	public function setDuration($duration) {
		$this->properties->set('duration', $duration);
		return $this;
	}


	/**
	 * Get the formative
	 *
	 * @return formative the formative value
	 */
	public function getFormative() {
		return $this->properties->get('formative');
	}

	/**
	 * Set the formative
	 *
	 * @param formative the formative value
	 *
	 * @return BaseTraining
	 */
	public function setFormative($formative) {
		$this->properties->set('formative', $formative);
		return $this;
	}


	/**
	 * Get the state
	 *
	 * @return state the state value
	 */
	public function getState() {
		return $this->properties->get('state');
	}

	/**
	 * Set the state
	 *
	 * @param state the state value
	 *
	 * @return BaseTraining
	 */
	public function setState($state) {
		$this->properties->set('state', $state);
		return $this;
	}


	public function __toString() {
				return $this->getName();
    }



}
