<?php
/**
 * BaseProject
 * Generated by Tyneo Base Tools
 *
 * @package     model
 * @author      Samuel Kauffmann <skauffmann@tyneo.net>
 * @copyright   Copyright (c) 2011, Samuel Kauffmann
 * @link        http://www.tyneo.net
 * @filesource	BaseProject.class.php
 */
namespace model\base;

/**
 * This class provides an object representation of a Project.
 *
 * @author		Samuel Kauffmann <skauffmann@tyneo.net>
 * @version		1.0
 */
abstract class BaseProject extends AbstractBaseObject {


	/**
	 * Get the id
	 *
	 * @return id the id value
	 */
	public function getId() {
		return $this->properties->get('id');
	}

	/**
	 * Set the id
	 *
	 * @param id the id value
	 *
	 * @return BaseProject
	 */
	public function setId($id) {
		$this->properties->set('id', $id);
		return $this;
	}


	/**
	 * Get the name
	 *
	 * @return name the name value
	 */
	public function getName() {
		return $this->properties->get('name');
	}

	/**
	 * Set the name
	 *
	 * @param name the name value
	 *
	 * @return BaseProject
	 */
	public function setName($name) {
		$this->properties->set('name', $name);
		return $this;
	}


	/**
	 * Get the description
	 *
	 * @return description the description value
	 */
	public function getDescription() {
		return $this->properties->get('description');
	}

	/**
	 * Set the description
	 *
	 * @param description the description value
	 *
	 * @return BaseProject
	 */
	public function setDescription($description) {
		$this->properties->set('description', $description);
		return $this;
	}


	/**
	 * Get the start_date
	 *
	 * @return start_date the start_date value
	 */
	public function getStartDate() {
		return $this->properties->get('start_date');
	}

	/**
	 * Set the start_date
	 *
	 * @param start_date the start_date value
	 *
	 * @return BaseProject
	 */
	public function setStartDate($start_date) {
		$this->properties->set('start_date', $start_date);
		return $this;
	}


	/**
	 * Get the end_date
	 *
	 * @return end_date the end_date value
	 */
	public function getEndDate() {
		return $this->properties->get('end_date');
	}

	/**
	 * Set the end_date
	 *
	 * @param end_date the end_date value
	 *
	 * @return BaseProject
	 */
	public function setEndDate($end_date) {
		$this->properties->set('end_date', $end_date);
		return $this;
	}


	/**
	 * Get the is_archived
	 *
	 * @return is_archived the is_archived value
	 */
	public function getIsArchived() {
		return $this->properties->get('is_archived');
	}

	/**
	 * Set the is_archived
	 *
	 * @param is_archived the is_archived value
	 *
	 * @return BaseProject
	 */
	public function setIsArchived($is_archived) {
		$this->properties->set('is_archived', $is_archived);
		return $this;
	}


	public function __toString() {
				return $this->getName();
    }



}
