<?php
/**
 * BaseWpkbLinks
 * Generated by Tyneo Base Tools
 *
 * @package     model
 * @author      Samuel Kauffmann <skauffmann@tyneo.net>
 * @copyright   Copyright (c) 2011, Samuel Kauffmann
 * @link        http://www.tyneo.net
 * @filesource	BaseWpkbLinks.class.php
 */
namespace model\base;

/**
 * This class provides an object representation of a WpkbLinks.
 *
 * @author		Samuel Kauffmann <skauffmann@tyneo.net>
 * @version		1.0
 */
abstract class BaseWpkbLinks extends AbstractBaseObject {


	/**
	 * Get the link_id
	 *
	 * @return link_id the link_id value
	 */
	public function getLinkId() {
		return $this->properties->get('link_id');
	}

	/**
	 * Set the link_id
	 *
	 * @param link_id the link_id value
	 *
	 * @return BaseWpkbLinks
	 */
	public function setLinkId($link_id) {
		$this->properties->set('link_id', $link_id);
		return $this;
	}


	/**
	 * Get the link_url
	 *
	 * @return link_url the link_url value
	 */
	public function getLinkUrl() {
		return $this->properties->get('link_url');
	}

	/**
	 * Set the link_url
	 *
	 * @param link_url the link_url value
	 *
	 * @return BaseWpkbLinks
	 */
	public function setLinkUrl($link_url) {
		$this->properties->set('link_url', $link_url);
		return $this;
	}


	/**
	 * Get the link_name
	 *
	 * @return link_name the link_name value
	 */
	public function getLinkName() {
		return $this->properties->get('link_name');
	}

	/**
	 * Set the link_name
	 *
	 * @param link_name the link_name value
	 *
	 * @return BaseWpkbLinks
	 */
	public function setLinkName($link_name) {
		$this->properties->set('link_name', $link_name);
		return $this;
	}


	/**
	 * Get the link_image
	 *
	 * @return link_image the link_image value
	 */
	public function getLinkImage() {
		return $this->properties->get('link_image');
	}

	/**
	 * Set the link_image
	 *
	 * @param link_image the link_image value
	 *
	 * @return BaseWpkbLinks
	 */
	public function setLinkImage($link_image) {
		$this->properties->set('link_image', $link_image);
		return $this;
	}


	/**
	 * Get the link_target
	 *
	 * @return link_target the link_target value
	 */
	public function getLinkTarget() {
		return $this->properties->get('link_target');
	}

	/**
	 * Set the link_target
	 *
	 * @param link_target the link_target value
	 *
	 * @return BaseWpkbLinks
	 */
	public function setLinkTarget($link_target) {
		$this->properties->set('link_target', $link_target);
		return $this;
	}


	/**
	 * Get the link_description
	 *
	 * @return link_description the link_description value
	 */
	public function getLinkDescription() {
		return $this->properties->get('link_description');
	}

	/**
	 * Set the link_description
	 *
	 * @param link_description the link_description value
	 *
	 * @return BaseWpkbLinks
	 */
	public function setLinkDescription($link_description) {
		$this->properties->set('link_description', $link_description);
		return $this;
	}


	/**
	 * Get the link_visible
	 *
	 * @return link_visible the link_visible value
	 */
	public function getLinkVisible() {
		return $this->properties->get('link_visible');
	}

	/**
	 * Set the link_visible
	 *
	 * @param link_visible the link_visible value
	 *
	 * @return BaseWpkbLinks
	 */
	public function setLinkVisible($link_visible) {
		$this->properties->set('link_visible', $link_visible);
		return $this;
	}


	/**
	 * Get the link_owner
	 *
	 * @return link_owner the link_owner value
	 */
	public function getLinkOwner() {
		return $this->properties->get('link_owner');
	}

	/**
	 * Set the link_owner
	 *
	 * @param link_owner the link_owner value
	 *
	 * @return BaseWpkbLinks
	 */
	public function setLinkOwner($link_owner) {
		$this->properties->set('link_owner', $link_owner);
		return $this;
	}


	/**
	 * Get the link_rating
	 *
	 * @return link_rating the link_rating value
	 */
	public function getLinkRating() {
		return $this->properties->get('link_rating');
	}

	/**
	 * Set the link_rating
	 *
	 * @param link_rating the link_rating value
	 *
	 * @return BaseWpkbLinks
	 */
	public function setLinkRating($link_rating) {
		$this->properties->set('link_rating', $link_rating);
		return $this;
	}


	/**
	 * Get the link_updated
	 *
	 * @return link_updated the link_updated value
	 */
	public function getLinkUpdated() {
		return $this->properties->get('link_updated');
	}

	/**
	 * Set the link_updated
	 *
	 * @param link_updated the link_updated value
	 *
	 * @return BaseWpkbLinks
	 */
	public function setLinkUpdated($link_updated) {
		$this->properties->set('link_updated', $link_updated);
		return $this;
	}


	/**
	 * Get the link_rel
	 *
	 * @return link_rel the link_rel value
	 */
	public function getLinkRel() {
		return $this->properties->get('link_rel');
	}

	/**
	 * Set the link_rel
	 *
	 * @param link_rel the link_rel value
	 *
	 * @return BaseWpkbLinks
	 */
	public function setLinkRel($link_rel) {
		$this->properties->set('link_rel', $link_rel);
		return $this;
	}


	/**
	 * Get the link_notes
	 *
	 * @return link_notes the link_notes value
	 */
	public function getLinkNotes() {
		return $this->properties->get('link_notes');
	}

	/**
	 * Set the link_notes
	 *
	 * @param link_notes the link_notes value
	 *
	 * @return BaseWpkbLinks
	 */
	public function setLinkNotes($link_notes) {
		$this->properties->set('link_notes', $link_notes);
		return $this;
	}


	/**
	 * Get the link_rss
	 *
	 * @return link_rss the link_rss value
	 */
	public function getLinkRss() {
		return $this->properties->get('link_rss');
	}

	/**
	 * Set the link_rss
	 *
	 * @param link_rss the link_rss value
	 *
	 * @return BaseWpkbLinks
	 */
	public function setLinkRss($link_rss) {
		$this->properties->set('link_rss', $link_rss);
		return $this;
	}

}
