<?php
/**
 * BaseCommentmeta
 * Generated by Tyneo Base Tools
 *
 * @package     model
 * @author      Samuel Kauffmann <skauffmann@tyneo.net>
 * @copyright   Copyright (c) 2011, Samuel Kauffmann
 * @link        http://www.tyneo.net
 * @filesource	BaseCommentmeta.class.php
 */
namespace model\base;

/**
 * This class provides an object representation of a Commentmeta.
 *
 * @author		Samuel Kauffmann <skauffmann@tyneo.net>
 * @version		1.0
 */
abstract class BaseCommentmeta extends AbstractBaseObject {


	/**
	 * Get the meta_id
	 *
	 * @return meta_id the meta_id value
	 */
	public function getMetaId() {
		return $this->properties->get('meta_id');
	}

	/**
	 * Set the meta_id
	 *
	 * @param meta_id the meta_id value
	 *
	 * @return BaseCommentmeta
	 */
	public function setMetaId($meta_id) {
		$this->properties->set('meta_id', $meta_id);
		return $this;
	}


	/**
	 * Get the comment_id
	 *
	 * @return comment_id the comment_id value
	 */
	public function getCommentId() {
		return $this->properties->get('comment_id');
	}

	/**
	 * Set the comment_id
	 *
	 * @param comment_id the comment_id value
	 *
	 * @return BaseCommentmeta
	 */
	public function setCommentId($comment_id) {
		$this->properties->set('comment_id', $comment_id);
		return $this;
	}


	/**
	 * Get the meta_key
	 *
	 * @return meta_key the meta_key value
	 */
	public function getMetaKey() {
		return $this->properties->get('meta_key');
	}

	/**
	 * Set the meta_key
	 *
	 * @param meta_key the meta_key value
	 *
	 * @return BaseCommentmeta
	 */
	public function setMetaKey($meta_key) {
		$this->properties->set('meta_key', $meta_key);
		return $this;
	}


	/**
	 * Get the meta_value
	 *
	 * @return meta_value the meta_value value
	 */
	public function getMetaValue() {
		return $this->properties->get('meta_value');
	}

	/**
	 * Set the meta_value
	 *
	 * @param meta_value the meta_value value
	 *
	 * @return BaseCommentmeta
	 */
	public function setMetaValue($meta_value) {
		$this->properties->set('meta_value', $meta_value);
		return $this;
	}

}
