<?php
/**
 * BaseWpkbOptionsManager
 * Generated by Tyneo Base Tools
 *
 * @package     model
 * @author      Samuel Kauffmann <skauffmann@tyneo.net>
 * @copyright   Copyright (c) 2011, Samuel Kauffmann
 * @link        http://www.tyneo.net
 * @filesource	BaseWpkbOptionsManager.class.php
 */
namespace model\base;

abstract class BaseWpkbOptionsManager extends AbstractBaseObjectManager {
	public function __construct(\framework\ApplicationContext $context) {
		parent::__construct($context);
		$this->setTableName('wpkb_options');
	}

	public function getWpkbOptionss() {
		$query = new \framework\query\QueryBuilder();
		$query->addSelect($this->getTableName().'.*');
		$query->addTable($this->getTableName());
		$results = $this->database->query($query->toSQL());
		return $this->getObjectsFromResult($results);
	}

	public function getWpkbOptions($id) {
		$query = new \framework\query\QueryBuilder();
		$query->addSelect($this->getTableName().'.*');
		$query->addTable($this->getTableName());
		if(!is_array($id)) {
			$query->addWhere($this->getTableName().'.id', \framework\query\operator\Operator::EQUAL, $id);
		} else {
			foreach ($id as $key => $value) {
				$query->addWhere($key, \framework\query\operator\Operator::EQUAL, $value);
			}
		}
		$object = $this->database->queryUniqueObject($query->toSQL());
		if($object != null) {
			return $this->getObjectFromRow($object);
		}
		return null;
	}

	protected function getUpdateQuery(\model\WpkbOptions $obj) {
		$query = new \framework\query\UpdateBuilder($this->getTableName());
					$query->setField('option_id', $obj->getOptionId());
							$query->setField('option_name', $obj->getOptionName());
							$query->setField('option_value', $obj->getOptionValue());
							$query->setField('autoload', $obj->getAutoload());

		foreach ($this->getIdFields() as $id) {
			$method = 'get'.$this->slugify($id);
			$query->addWhere($id, \framework\query\operator\Operator::EQUAL, $obj->$method());
		}
		return $query;
	}

	protected function update(\model\WpkbOptions $obj) {
		$query = $this->getUpdateQuery($obj);
		$this->database->execute($query->toSQL());
	}

	protected function getCreateQuery(\model\WpkbOptions $obj) {
		$query = new \framework\query\CreateBuilder($this->getTableName());
				$query->setField('option_id', $obj->getOptionId());
					$query->setField('option_name', $obj->getOptionName());
					$query->setField('option_value', $obj->getOptionValue());
					$query->setField('autoload', $obj->getAutoload());

		return $query;
	}

	protected function create(\model\WpkbOptions $obj) {
		$query = $this->getCreateQuery($obj);
		$this->database->execute($query->toSQL());
		$obj->setNew(false);
	}

	protected function getObjectFromRow($row) {
		$object = new \model\WpkbOptions();
			$object->setOptionId(\framework\utility\String::fromSQL($row->option_id));
			$object->setOptionName(\framework\utility\String::fromSQL($row->option_name));
			$object->setOptionValue(\framework\utility\String::fromSQL($row->option_value));
			$object->setAutoload(\framework\utility\String::fromSQL($row->autoload));

		$object->setNew(false);
		return $object;
	}

}
