<?php
/**
 * BaseWpkbUsers
 * Generated by Tyneo Base Tools
 *
 * @package     model
 * @author      Samuel Kauffmann <skauffmann@tyneo.net>
 * @copyright   Copyright (c) 2011, Samuel Kauffmann
 * @link        http://www.tyneo.net
 * @filesource	BaseWpkbUsers.class.php
 */
namespace model\base;

/**
 * This class provides an object representation of a WpkbUsers.
 *
 * @author		Samuel Kauffmann <skauffmann@tyneo.net>
 * @version		1.0
 */
abstract class BaseWpkbUsers extends AbstractBaseObject {


	/**
	 * Get the id
	 *
	 * @return id the id value
	 */
	public function getId() {
		return $this->properties->get('id');
	}

	/**
	 * Set the id
	 *
	 * @param id the id value
	 *
	 * @return BaseWpkbUsers
	 */
	public function setId($id) {
		$this->properties->set('id', $id);
		return $this;
	}


	/**
	 * Get the user_login
	 *
	 * @return user_login the user_login value
	 */
	public function getUserLogin() {
		return $this->properties->get('user_login');
	}

	/**
	 * Set the user_login
	 *
	 * @param user_login the user_login value
	 *
	 * @return BaseWpkbUsers
	 */
	public function setUserLogin($user_login) {
		$this->properties->set('user_login', $user_login);
		return $this;
	}


	/**
	 * Get the user_pass
	 *
	 * @return user_pass the user_pass value
	 */
	public function getUserPass() {
		return $this->properties->get('user_pass');
	}

	/**
	 * Set the user_pass
	 *
	 * @param user_pass the user_pass value
	 *
	 * @return BaseWpkbUsers
	 */
	public function setUserPass($user_pass) {
		$this->properties->set('user_pass', $user_pass);
		return $this;
	}


	/**
	 * Get the user_nicename
	 *
	 * @return user_nicename the user_nicename value
	 */
	public function getUserNicename() {
		return $this->properties->get('user_nicename');
	}

	/**
	 * Set the user_nicename
	 *
	 * @param user_nicename the user_nicename value
	 *
	 * @return BaseWpkbUsers
	 */
	public function setUserNicename($user_nicename) {
		$this->properties->set('user_nicename', $user_nicename);
		return $this;
	}


	/**
	 * Get the user_email
	 *
	 * @return user_email the user_email value
	 */
	public function getUserEmail() {
		return $this->properties->get('user_email');
	}

	/**
	 * Set the user_email
	 *
	 * @param user_email the user_email value
	 *
	 * @return BaseWpkbUsers
	 */
	public function setUserEmail($user_email) {
		$this->properties->set('user_email', $user_email);
		return $this;
	}


	/**
	 * Get the user_url
	 *
	 * @return user_url the user_url value
	 */
	public function getUserUrl() {
		return $this->properties->get('user_url');
	}

	/**
	 * Set the user_url
	 *
	 * @param user_url the user_url value
	 *
	 * @return BaseWpkbUsers
	 */
	public function setUserUrl($user_url) {
		$this->properties->set('user_url', $user_url);
		return $this;
	}


	/**
	 * Get the user_registered
	 *
	 * @return user_registered the user_registered value
	 */
	public function getUserRegistered() {
		return $this->properties->get('user_registered');
	}

	/**
	 * Set the user_registered
	 *
	 * @param user_registered the user_registered value
	 *
	 * @return BaseWpkbUsers
	 */
	public function setUserRegistered($user_registered) {
		$this->properties->set('user_registered', $user_registered);
		return $this;
	}


	/**
	 * Get the user_activation_key
	 *
	 * @return user_activation_key the user_activation_key value
	 */
	public function getUserActivationKey() {
		return $this->properties->get('user_activation_key');
	}

	/**
	 * Set the user_activation_key
	 *
	 * @param user_activation_key the user_activation_key value
	 *
	 * @return BaseWpkbUsers
	 */
	public function setUserActivationKey($user_activation_key) {
		$this->properties->set('user_activation_key', $user_activation_key);
		return $this;
	}


	/**
	 * Get the user_status
	 *
	 * @return user_status the user_status value
	 */
	public function getUserStatus() {
		return $this->properties->get('user_status');
	}

	/**
	 * Set the user_status
	 *
	 * @param user_status the user_status value
	 *
	 * @return BaseWpkbUsers
	 */
	public function setUserStatus($user_status) {
		$this->properties->set('user_status', $user_status);
		return $this;
	}


	/**
	 * Get the display_name
	 *
	 * @return display_name the display_name value
	 */
	public function getDisplayName() {
		return $this->properties->get('display_name');
	}

	/**
	 * Set the display_name
	 *
	 * @param display_name the display_name value
	 *
	 * @return BaseWpkbUsers
	 */
	public function setDisplayName($display_name) {
		$this->properties->set('display_name', $display_name);
		return $this;
	}

}
