<?php
/**
 * BaseCompany
 * Generated by Tyneo Base Tools
 *
 * @package     model
 * @author      Samuel Kauffmann <skauffmann@tyneo.net>
 * @copyright   Copyright (c) 2011, Samuel Kauffmann
 * @link        http://www.tyneo.net
 * @filesource	BaseCompany.class.php
 */
namespace model\base;

/**
 * This class provides an object representation of a Company.
 *
 * @author		Samuel Kauffmann <skauffmann@tyneo.net>
 * @version		1.0
 */
abstract class BaseCompany extends AbstractBaseObject {


	/**
	 * Get the id
	 *
	 * @return id the id value
	 */
	public function getId() {
		return $this->properties->get('id');
	}

	/**
	 * Set the id
	 *
	 * @param id the id value
	 *
	 * @return BaseCompany
	 */
	public function setId($id) {
		$this->properties->set('id', $id);
		return $this;
	}


	/**
	 * Get the name
	 *
	 * @return name the name value
	 */
	public function getName() {
		return $this->properties->get('name');
	}

	/**
	 * Set the name
	 *
	 * @param name the name value
	 *
	 * @return BaseCompany
	 */
	public function setName($name) {
		$this->properties->set('name', $name);
		return $this;
	}


	/**
	 * Get the description
	 *
	 * @return description the description value
	 */
	public function getDescription() {
		return $this->properties->get('description');
	}

	/**
	 * Set the description
	 *
	 * @param description the description value
	 *
	 * @return BaseCompany
	 */
	public function setDescription($description) {
		$this->properties->set('description', $description);
		return $this;
	}


	/**
	 * Get the address
	 *
	 * @return address the address value
	 */
	public function getAddress() {
		return $this->properties->get('address');
	}

	/**
	 * Set the address
	 *
	 * @param address the address value
	 *
	 * @return BaseCompany
	 */
	public function setAddress($address) {
		$this->properties->set('address', $address);
		return $this;
	}


	/**
	 * Get the city
	 *
	 * @return city the city value
	 */
	public function getCity() {
		return $this->properties->get('city');
	}

	/**
	 * Set the city
	 *
	 * @param city the city value
	 *
	 * @return BaseCompany
	 */
	public function setCity($city) {
		$this->properties->set('city', $city);
		return $this;
	}


	/**
	 * Get the postal_code
	 *
	 * @return postal_code the postal_code value
	 */
	public function getPostalCode() {
		return $this->properties->get('postal_code');
	}

	/**
	 * Set the postal_code
	 *
	 * @param postal_code the postal_code value
	 *
	 * @return BaseCompany
	 */
	public function setPostalCode($postal_code) {
		$this->properties->set('postal_code', $postal_code);
		return $this;
	}


	/**
	 * Get the country
	 *
	 * @return country the country value
	 */
	public function getCountry() {
		return $this->properties->get('country');
	}

	/**
	 * Set the country
	 *
	 * @param country the country value
	 *
	 * @return BaseCompany
	 */
	public function setCountry($country) {
		$this->properties->set('country', $country);
		return $this;
	}


	/**
	 * Get the tel
	 *
	 * @return tel the tel value
	 */
	public function getTel() {
		return $this->properties->get('tel');
	}

	/**
	 * Set the tel
	 *
	 * @param tel the tel value
	 *
	 * @return BaseCompany
	 */
	public function setTel($tel) {
		$this->properties->set('tel', $tel);
		return $this;
	}


	/**
	 * Get the fax
	 *
	 * @return fax the fax value
	 */
	public function getFax() {
		return $this->properties->get('fax');
	}

	/**
	 * Set the fax
	 *
	 * @param fax the fax value
	 *
	 * @return BaseCompany
	 */
	public function setFax($fax) {
		$this->properties->set('fax', $fax);
		return $this;
	}


	/**
	 * Get the website
	 *
	 * @return website the website value
	 */
	public function getWebsite() {
		return $this->properties->get('website');
	}

	/**
	 * Set the website
	 *
	 * @param website the website value
	 *
	 * @return BaseCompany
	 */
	public function setWebsite($website) {
		$this->properties->set('website', $website);
		return $this;
	}


	/**
	 * Get the vat_number
	 *
	 * @return vat_number the vat_number value
	 */
	public function getVatNumber() {
		return $this->properties->get('vat_number');
	}

	/**
	 * Set the vat_number
	 *
	 * @param vat_number the vat_number value
	 *
	 * @return BaseCompany
	 */
	public function setVatNumber($vat_number) {
		$this->properties->set('vat_number', $vat_number);
		return $this;
	}


	/**
	 * Get the contact_id
	 *
	 * @return contact_id the contact_id value
	 */
	public function getContactId() {
		return $this->properties->get('contact_id');
	}

	/**
	 * Set the contact_id
	 *
	 * @param contact_id the contact_id value
	 *
	 * @return BaseCompany
	 */
	public function setContactId($contact_id) {
		$this->properties->set('contact_id', $contact_id);
		return $this;
	}


	/**
	 * Get the langage
	 *
	 * @return langage the langage value
	 */
	public function getLangage() {
		return $this->properties->get('langage');
	}

	/**
	 * Set the langage
	 *
	 * @param langage the langage value
	 *
	 * @return BaseCompany
	 */
	public function setLangage($langage) {
		$this->properties->set('langage', $langage);
		return $this;
	}


	public function __toString() {
				return $this->getName();
    }



	public function getContact() {
		$contactManager = new \model\ContactManager();
		return $contactManager->getContact($this->getContactId());
	}

}
