<?php
/**
 * BaseComments
 * Generated by Tyneo Base Tools
 *
 * @package     model
 * @author      Samuel Kauffmann <skauffmann@tyneo.net>
 * @copyright   Copyright (c) 2011, Samuel Kauffmann
 * @link        http://www.tyneo.net
 * @filesource	BaseComments.class.php
 */
namespace model\base;

/**
 * This class provides an object representation of a Comments.
 *
 * @author		Samuel Kauffmann <skauffmann@tyneo.net>
 * @version		1.0
 */
abstract class BaseComments extends AbstractBaseObject {


	/**
	 * Get the comment_id
	 *
	 * @return comment_id the comment_id value
	 */
	public function getCommentId() {
		return $this->properties->get('comment_id');
	}

	/**
	 * Set the comment_id
	 *
	 * @param comment_id the comment_id value
	 *
	 * @return BaseComments
	 */
	public function setCommentId($comment_id) {
		$this->properties->set('comment_id', $comment_id);
		return $this;
	}


	/**
	 * Get the comment_post_id
	 *
	 * @return comment_post_id the comment_post_id value
	 */
	public function getCommentPostId() {
		return $this->properties->get('comment_post_id');
	}

	/**
	 * Set the comment_post_id
	 *
	 * @param comment_post_id the comment_post_id value
	 *
	 * @return BaseComments
	 */
	public function setCommentPostId($comment_post_id) {
		$this->properties->set('comment_post_id', $comment_post_id);
		return $this;
	}


	/**
	 * Get the comment_author
	 *
	 * @return comment_author the comment_author value
	 */
	public function getCommentAuthor() {
		return $this->properties->get('comment_author');
	}

	/**
	 * Set the comment_author
	 *
	 * @param comment_author the comment_author value
	 *
	 * @return BaseComments
	 */
	public function setCommentAuthor($comment_author) {
		$this->properties->set('comment_author', $comment_author);
		return $this;
	}


	/**
	 * Get the comment_author_email
	 *
	 * @return comment_author_email the comment_author_email value
	 */
	public function getCommentAuthorEmail() {
		return $this->properties->get('comment_author_email');
	}

	/**
	 * Set the comment_author_email
	 *
	 * @param comment_author_email the comment_author_email value
	 *
	 * @return BaseComments
	 */
	public function setCommentAuthorEmail($comment_author_email) {
		$this->properties->set('comment_author_email', $comment_author_email);
		return $this;
	}


	/**
	 * Get the comment_author_url
	 *
	 * @return comment_author_url the comment_author_url value
	 */
	public function getCommentAuthorUrl() {
		return $this->properties->get('comment_author_url');
	}

	/**
	 * Set the comment_author_url
	 *
	 * @param comment_author_url the comment_author_url value
	 *
	 * @return BaseComments
	 */
	public function setCommentAuthorUrl($comment_author_url) {
		$this->properties->set('comment_author_url', $comment_author_url);
		return $this;
	}


	/**
	 * Get the comment_author_ip
	 *
	 * @return comment_author_ip the comment_author_ip value
	 */
	public function getCommentAuthorIp() {
		return $this->properties->get('comment_author_ip');
	}

	/**
	 * Set the comment_author_ip
	 *
	 * @param comment_author_ip the comment_author_ip value
	 *
	 * @return BaseComments
	 */
	public function setCommentAuthorIp($comment_author_ip) {
		$this->properties->set('comment_author_ip', $comment_author_ip);
		return $this;
	}


	/**
	 * Get the comment_date
	 *
	 * @return comment_date the comment_date value
	 */
	public function getCommentDate() {
		return $this->properties->get('comment_date');
	}

	/**
	 * Set the comment_date
	 *
	 * @param comment_date the comment_date value
	 *
	 * @return BaseComments
	 */
	public function setCommentDate($comment_date) {
		$this->properties->set('comment_date', $comment_date);
		return $this;
	}


	/**
	 * Get the comment_date_gmt
	 *
	 * @return comment_date_gmt the comment_date_gmt value
	 */
	public function getCommentDateGmt() {
		return $this->properties->get('comment_date_gmt');
	}

	/**
	 * Set the comment_date_gmt
	 *
	 * @param comment_date_gmt the comment_date_gmt value
	 *
	 * @return BaseComments
	 */
	public function setCommentDateGmt($comment_date_gmt) {
		$this->properties->set('comment_date_gmt', $comment_date_gmt);
		return $this;
	}


	/**
	 * Get the comment_content
	 *
	 * @return comment_content the comment_content value
	 */
	public function getCommentContent() {
		return $this->properties->get('comment_content');
	}

	/**
	 * Set the comment_content
	 *
	 * @param comment_content the comment_content value
	 *
	 * @return BaseComments
	 */
	public function setCommentContent($comment_content) {
		$this->properties->set('comment_content', $comment_content);
		return $this;
	}


	/**
	 * Get the comment_karma
	 *
	 * @return comment_karma the comment_karma value
	 */
	public function getCommentKarma() {
		return $this->properties->get('comment_karma');
	}

	/**
	 * Set the comment_karma
	 *
	 * @param comment_karma the comment_karma value
	 *
	 * @return BaseComments
	 */
	public function setCommentKarma($comment_karma) {
		$this->properties->set('comment_karma', $comment_karma);
		return $this;
	}


	/**
	 * Get the comment_approved
	 *
	 * @return comment_approved the comment_approved value
	 */
	public function getCommentApproved() {
		return $this->properties->get('comment_approved');
	}

	/**
	 * Set the comment_approved
	 *
	 * @param comment_approved the comment_approved value
	 *
	 * @return BaseComments
	 */
	public function setCommentApproved($comment_approved) {
		$this->properties->set('comment_approved', $comment_approved);
		return $this;
	}


	/**
	 * Get the comment_agent
	 *
	 * @return comment_agent the comment_agent value
	 */
	public function getCommentAgent() {
		return $this->properties->get('comment_agent');
	}

	/**
	 * Set the comment_agent
	 *
	 * @param comment_agent the comment_agent value
	 *
	 * @return BaseComments
	 */
	public function setCommentAgent($comment_agent) {
		$this->properties->set('comment_agent', $comment_agent);
		return $this;
	}


	/**
	 * Get the comment_type
	 *
	 * @return comment_type the comment_type value
	 */
	public function getCommentType() {
		return $this->properties->get('comment_type');
	}

	/**
	 * Set the comment_type
	 *
	 * @param comment_type the comment_type value
	 *
	 * @return BaseComments
	 */
	public function setCommentType($comment_type) {
		$this->properties->set('comment_type', $comment_type);
		return $this;
	}


	/**
	 * Get the comment_parent
	 *
	 * @return comment_parent the comment_parent value
	 */
	public function getCommentParent() {
		return $this->properties->get('comment_parent');
	}

	/**
	 * Set the comment_parent
	 *
	 * @param comment_parent the comment_parent value
	 *
	 * @return BaseComments
	 */
	public function setCommentParent($comment_parent) {
		$this->properties->set('comment_parent', $comment_parent);
		return $this;
	}


	/**
	 * Get the user_id
	 *
	 * @return user_id the user_id value
	 */
	public function getUserId() {
		return $this->properties->get('user_id');
	}

	/**
	 * Set the user_id
	 *
	 * @param user_id the user_id value
	 *
	 * @return BaseComments
	 */
	public function setUserId($user_id) {
		$this->properties->set('user_id', $user_id);
		return $this;
	}

}
