<?php
/**
 * BaseWpkbOptions
 * Generated by Tyneo Base Tools
 *
 * @package     model
 * @author      Samuel Kauffmann <skauffmann@tyneo.net>
 * @copyright   Copyright (c) 2011, Samuel Kauffmann
 * @link        http://www.tyneo.net
 * @filesource	BaseWpkbOptions.class.php
 */
namespace model\base;

/**
 * This class provides an object representation of a WpkbOptions.
 *
 * @author		Samuel Kauffmann <skauffmann@tyneo.net>
 * @version		1.0
 */
abstract class BaseWpkbOptions extends AbstractBaseObject {


	/**
	 * Get the option_id
	 *
	 * @return option_id the option_id value
	 */
	public function getOptionId() {
		return $this->properties->get('option_id');
	}

	/**
	 * Set the option_id
	 *
	 * @param option_id the option_id value
	 *
	 * @return BaseWpkbOptions
	 */
	public function setOptionId($option_id) {
		$this->properties->set('option_id', $option_id);
		return $this;
	}


	/**
	 * Get the option_name
	 *
	 * @return option_name the option_name value
	 */
	public function getOptionName() {
		return $this->properties->get('option_name');
	}

	/**
	 * Set the option_name
	 *
	 * @param option_name the option_name value
	 *
	 * @return BaseWpkbOptions
	 */
	public function setOptionName($option_name) {
		$this->properties->set('option_name', $option_name);
		return $this;
	}


	/**
	 * Get the option_value
	 *
	 * @return option_value the option_value value
	 */
	public function getOptionValue() {
		return $this->properties->get('option_value');
	}

	/**
	 * Set the option_value
	 *
	 * @param option_value the option_value value
	 *
	 * @return BaseWpkbOptions
	 */
	public function setOptionValue($option_value) {
		$this->properties->set('option_value', $option_value);
		return $this;
	}


	/**
	 * Get the autoload
	 *
	 * @return autoload the autoload value
	 */
	public function getAutoload() {
		return $this->properties->get('autoload');
	}

	/**
	 * Set the autoload
	 *
	 * @param autoload the autoload value
	 *
	 * @return BaseWpkbOptions
	 */
	public function setAutoload($autoload) {
		$this->properties->set('autoload', $autoload);
		return $this;
	}

}
