<?php
/**
 * BaseMailinglist
 * Generated by Tyneo Base Tools
 *
 * @package     model
 * @author      Samuel Kauffmann <skauffmann@tyneo.net>
 * @copyright   Copyright (c) 2011, Samuel Kauffmann
 * @link        http://www.tyneo.net
 * @filesource	BaseMailinglist.class.php
 */
namespace model\base;

/**
 * This class provides an object representation of a Mailinglist.
 *
 * @author		Samuel Kauffmann <skauffmann@tyneo.net>
 * @version		1.0
 */
abstract class BaseMailinglist extends AbstractBaseObject {


	/**
	 * Get the id
	 *
	 * @return id the id value
	 */
	public function getId() {
		return $this->properties->get('id');
	}

	/**
	 * Set the id
	 *
	 * @param id the id value
	 *
	 * @return BaseMailinglist
	 */
	public function setId($id) {
		$this->properties->set('id', $id);
		return $this;
	}


	/**
	 * Get the mail
	 *
	 * @return mail the mail value
	 */
	public function getMail() {
		return $this->properties->get('mail');
	}

	/**
	 * Set the mail
	 *
	 * @param mail the mail value
	 *
	 * @return BaseMailinglist
	 */
	public function setMail($mail) {
		$this->properties->set('mail', $mail);
		return $this;
	}


	/**
	 * Get the state
	 *
	 * @return state the state value
	 */
	public function getState() {
		return $this->properties->get('state');
	}

	/**
	 * Set the state
	 *
	 * @param state the state value
	 *
	 * @return BaseMailinglist
	 */
	public function setState($state) {
		$this->properties->set('state', $state);
		return $this;
	}


	/**
	 * Get the firstname
	 *
	 * @return firstname the firstname value
	 */
	public function getFirstname() {
		return $this->properties->get('firstname');
	}

	/**
	 * Set the firstname
	 *
	 * @param firstname the firstname value
	 *
	 * @return BaseMailinglist
	 */
	public function setFirstname($firstname) {
		$this->properties->set('firstname', $firstname);
		return $this;
	}


	/**
	 * Get the lastname
	 *
	 * @return lastname the lastname value
	 */
	public function getLastname() {
		return $this->properties->get('lastname');
	}

	/**
	 * Set the lastname
	 *
	 * @param lastname the lastname value
	 *
	 * @return BaseMailinglist
	 */
	public function setLastname($lastname) {
		$this->properties->set('lastname', $lastname);
		return $this;
	}


	/**
	 * Get the company
	 *
	 * @return company the company value
	 */
	public function getCompany() {
		return $this->properties->get('company');
	}

	/**
	 * Set the company
	 *
	 * @param company the company value
	 *
	 * @return BaseMailinglist
	 */
	public function setCompany($company) {
		$this->properties->set('company', $company);
		return $this;
	}


	/**
	 * Get the position
	 *
	 * @return position the position value
	 */
	public function getPosition() {
		return $this->properties->get('position');
	}

	/**
	 * Set the position
	 *
	 * @param position the position value
	 *
	 * @return BaseMailinglist
	 */
	public function setPosition($position) {
		$this->properties->set('position', $position);
		return $this;
	}


	/**
	 * Get the interest
	 *
	 * @return interest the interest value
	 */
	public function getInterest() {
		return $this->properties->get('interest');
	}

	/**
	 * Set the interest
	 *
	 * @param interest the interest value
	 *
	 * @return BaseMailinglist
	 */
	public function setInterest($interest) {
		$this->properties->set('interest', $interest);
		return $this;
	}


	/**
	 * Get the activation_code
	 *
	 * @return activation_code the activation_code value
	 */
	public function getActivationCode() {
		return $this->properties->get('activation_code');
	}

	/**
	 * Set the activation_code
	 *
	 * @param activation_code the activation_code value
	 *
	 * @return BaseMailinglist
	 */
	public function setActivationCode($activation_code) {
		$this->properties->set('activation_code', $activation_code);
		return $this;
	}


	public function __toString() {
				return $this->getId();
    }



}
