<?php
/**
 * BaseSession
 * Generated by Tyneo Base Tools
 *
 * @package     model
 * @author      Samuel Kauffmann <skauffmann@tyneo.net>
 * @copyright   Copyright (c) 2011, Samuel Kauffmann
 * @link        http://www.tyneo.net
 * @filesource	BaseSession.class.php
 */
namespace model\base;

/**
 * This class provides an object representation of a Session.
 *
 * @author		Samuel Kauffmann <skauffmann@tyneo.net>
 * @version		1.0
 */
abstract class BaseSession extends AbstractBaseObject {


	/**
	 * Get the sid
	 *
	 * @return sid the sid value
	 */
	public function getSid() {
		return $this->properties->get('sid');
	}

	/**
	 * Set the sid
	 *
	 * @param sid the sid value
	 *
	 * @return BaseSession
	 */
	public function setSid($sid) {
		$this->properties->set('sid', $sid);
		return $this;
	}


	/**
	 * Get the user_id
	 *
	 * @return user_id the user_id value
	 */
	public function getUserId() {
		return $this->properties->get('user_id');
	}

	/**
	 * Set the user_id
	 *
	 * @param user_id the user_id value
	 *
	 * @return BaseSession
	 */
	public function setUserId($user_id) {
		$this->properties->set('user_id', $user_id);
		return $this;
	}


	/**
	 * Get the hostname
	 *
	 * @return hostname the hostname value
	 */
	public function getHostname() {
		return $this->properties->get('hostname');
	}

	/**
	 * Set the hostname
	 *
	 * @param hostname the hostname value
	 *
	 * @return BaseSession
	 */
	public function setHostname($hostname) {
		$this->properties->set('hostname', $hostname);
		return $this;
	}


	/**
	 * Get the timestamp
	 *
	 * @return timestamp the timestamp value
	 */
	public function getTimestamp() {
		return $this->properties->get('timestamp');
	}

	/**
	 * Set the timestamp
	 *
	 * @param timestamp the timestamp value
	 *
	 * @return BaseSession
	 */
	public function setTimestamp($timestamp) {
		$this->properties->set('timestamp', $timestamp);
		return $this;
	}


	/**
	 * Get the data
	 *
	 * @return data the data value
	 */
	public function getData() {
		return $this->properties->get('data');
	}

	/**
	 * Set the data
	 *
	 * @param data the data value
	 *
	 * @return BaseSession
	 */
	public function setData($data) {
		$this->properties->set('data', $data);
		return $this;
	}


	public function __toString() {
				return $this->get();
    }



	public function getUser() {
		$userManager = new \model\UserManager();
		return $userManager->getUser($this->getUserId());
	}

}
