<?php
/**
 * BaseUserprofile
 * Generated by Tyneo Base Tools
 *
 * @package     model
 * @author      Samuel Kauffmann <skauffmann@tyneo.net>
 * @copyright   Copyright (c) 2011, Samuel Kauffmann
 * @link        http://www.tyneo.net
 * @filesource	BaseUserprofile.class.php
 */
namespace model\base;

/**
 * This class provides an object representation of a Userprofile.
 *
 * @author		Samuel Kauffmann <skauffmann@tyneo.net>
 * @version		1.0
 */
abstract class BaseUserprofile extends AbstractBaseObject {


	/**
	 * Get the user_id
	 *
	 * @return user_id the user_id value
	 */
	public function getUserId() {
		return $this->properties->get('user_id');
	}

	/**
	 * Set the user_id
	 *
	 * @param user_id the user_id value
	 *
	 * @return BaseUserprofile
	 */
	public function setUserId($user_id) {
		$this->properties->set('user_id', $user_id);
		return $this;
	}


	/**
	 * Get the profile_id
	 *
	 * @return profile_id the profile_id value
	 */
	public function getProfileId() {
		return $this->properties->get('profile_id');
	}

	/**
	 * Set the profile_id
	 *
	 * @param profile_id the profile_id value
	 *
	 * @return BaseUserprofile
	 */
	public function setProfileId($profile_id) {
		$this->properties->set('profile_id', $profile_id);
		return $this;
	}


	public function __toString() {
				return $this->get();
    }



	public function getUser() {
		$userManager = new \model\UserManager();
		return $userManager->getUser($this->getUserId());
	}

	public function getProfile() {
		$profileManager = new \model\ProfileManager();
		return $profileManager->getProfile($this->getProfileId());
	}

}
