<?php
/**
 * BaseEditor
 * Generated by Tyneo Base Tools
 *
 * @package     model
 * @author      Samuel Kauffmann <skauffmann@tyneo.net>
 * @copyright   Copyright (c) 2011, Samuel Kauffmann
 * @link        http://www.tyneo.net
 * @filesource	BaseEditor.class.php
 */
namespace model\base;

/**
 * This class provides an object representation of a Editor.
 *
 * @author		Samuel Kauffmann <skauffmann@tyneo.net>
 * @version		1.0
 */
abstract class BaseEditor extends AbstractBaseObject {


	/**
	 * Get the id
	 *
	 * @return id the id value
	 */
	public function getId() {
		return $this->properties->get('id');
	}

	/**
	 * Set the id
	 *
	 * @param id the id value
	 *
	 * @return BaseEditor
	 */
	public function setId($id) {
		$this->properties->set('id', $id);
		return $this;
	}


	/**
	 * Get the name
	 *
	 * @return name the name value
	 */
	public function getName() {
		return $this->properties->get('name');
	}

	/**
	 * Set the name
	 *
	 * @param name the name value
	 *
	 * @return BaseEditor
	 */
	public function setName($name) {
		$this->properties->set('name', $name);
		return $this;
	}


	/**
	 * Get the description
	 *
	 * @return description the description value
	 */
	public function getDescription() {
		return $this->properties->get('description');
	}

	/**
	 * Set the description
	 *
	 * @param description the description value
	 *
	 * @return BaseEditor
	 */
	public function setDescription($description) {
		$this->properties->set('description', $description);
		return $this;
	}


	/**
	 * Get the site
	 *
	 * @return site the site value
	 */
	public function getSite() {
		return $this->properties->get('site');
	}

	/**
	 * Set the site
	 *
	 * @param site the site value
	 *
	 * @return BaseEditor
	 */
	public function setSite($site) {
		$this->properties->set('site', $site);
		return $this;
	}


	public function __toString() {
				return $this->getName();
    }



}
