<?php
/**
 * BaseAccountingManager
 * Generated by Tyneo Base Tools
 *
 * @package     model
 * @author      Samuel Kauffmann <skauffmann@tyneo.net>
 * @copyright   Copyright (c) 2011, Samuel Kauffmann
 * @link        http://www.tyneo.net
 * @filesource	BaseAccountingManager.class.php
 */
namespace model\base;

abstract class BaseAccountingManager extends AbstractBaseObjectManager {
	public function __construct(\framework\ApplicationContext $context) {
		parent::__construct($context);
		$this->setTableName('accounting');
	}

	public function getAccountings() {
		$query = new \framework\query\QueryBuilder();
		$query->addSelect($this->getTableName().'.*');
		$query->addTable($this->getTableName());
		$results = $this->database->query($query->toSQL());
		return $this->getObjectsFromResult($results);
	}


	/**
	 * Returns a limited and filter number of Accountings	 *
	 * @param $start Number Index where we start to display Accountings (by default 0)
	 * @param $maxperpage Number Maximum number of item per page
	 * @param $filter String null or a Accounting filter
	 */
	public function getLimitedAccountings($start, $maxperpage, $filter) {
		if($maxperpage == null) $maxperpage = $this->context->getConfiguration()->get('max_per_page', 25);
		if($start == null) $start = 0;

		$query = new \framework\query\QueryBuilder();
		$query->addSelect($this->getTableName().'.*');
		$query->addTable($this->getTableName());

		if($filter != null) {
			$f = new \model\AccountingFilter($filter);
			$f->apply($query);
		}

		$query->setStart($start)->setMaxPerPage($maxperpage);

		$results = $this->database->query($query->toSQL());
		return $this->getObjectsFromResult($results);
	}

	public function countLimitedAccountings($filter) {
		$query = new \framework\query\QueryBuilder();
		$query->addSelectCount($this->getTableName().'.id', 'total', true);
		$query->addTable($this->getTableName());

		if($filter != null) {
			$f = new \model\AccountingFilter($filter);
			$f->apply($query);
		}

		return $this->database->queryUniqueObject($query->toSQL())->total;
	}

	public function countAccountings() {
		$query = new \framework\query\QueryBuilder();
		$query->addSelectCount($this->getTableName().'.id', 'total', true);
		$query->addTable($this->getTableName());
		return $this->database->queryUniqueObject($query->toSQL())->total;
	}

	public function getAccounting($id) {
		$query = new \framework\query\QueryBuilder();
		$query->addSelect($this->getTableName().'.*');
		$query->addTable($this->getTableName());
		if(!is_array($id)) {
			$query->addWhere($this->getTableName().'.id', \framework\query\operator\Operator::EQUAL, $id);
		} else {
			foreach ($id as $key => $value) {
				$query->addWhere($key, \framework\query\operator\Operator::EQUAL, $value);
			}
		}
		$object = $this->database->queryUniqueObject($query->toSQL());
		if($object != null) {
			return $this->getObjectFromRow($object);
		}
		return null;
	}

	protected function getUpdateQuery(\model\Accounting $obj) {
		$query = new \framework\query\UpdateBuilder($this->getTableName());
					$query->setField('id', $obj->getId());
							$query->setField('name', $obj->getName());
							$query->setField('description', $obj->getDescription());
							$query->setField('date', $obj->getDate());
							$query->setField('amount', $obj->getAmount());
							$query->setField('vat', $obj->getVat());
							$query->setField('is_chargeable', $obj->getIsChargeable());
							$query->setField('nature', $obj->getNature());
							$query->setField('account_id', $obj->getAccountId());
							$query->setField('project_id', $obj->getProjectId());
							$query->setField('created_date', $obj->getCreatedDate());
							$query->setField('updated_date', 'CURDATE()', true);

		foreach ($this->getIdFields() as $id) {
			$method = 'get'.$this->slugify($id);
			$query->addWhere($id, \framework\query\operator\Operator::EQUAL, $obj->$method());
		}
		return $query;
	}

	protected function update(\model\Accounting $obj) {
		$query = $this->getUpdateQuery($obj);
		return $this->database->execute($query->toSQL());
	}

	protected function getCreateQuery(\model\Accounting $obj) {
		$query = new \framework\query\CreateBuilder($this->getTableName());
				$query->setField('id', $obj->getId());
					$query->setField('name', $obj->getName());
					$query->setField('description', $obj->getDescription());
					$query->setField('date', $obj->getDate());
					$query->setField('amount', $obj->getAmount());
					$query->setField('vat', $obj->getVat());
					$query->setField('is_chargeable', $obj->getIsChargeable());
					$query->setField('nature', $obj->getNature());
					$query->setField('account_id', $obj->getAccountId());
					$query->setField('project_id', $obj->getProjectId());
					$query->setField('created_date', 'CURDATE()', true);
					$query->setField('updated_date', 'CURDATE()', true);

		return $query;
	}

	protected function create(\model\Accounting $obj) {
		$query = $this->getCreateQuery($obj);

		if($this->database->execute($query->toSQL())) {
			$obj->setNew(false);
			return true;
		}
		return false;
	}

	public function delete(\model\Accounting $obj) {
		$query = new \framework\query\DeleteBuilder($this->getTableName());
		foreach ($this->getIdFields() as $id) {
			$method = 'get'.$this->slugify($id);
			$query->addWhere($id, \framework\query\operator\Operator::EQUAL, $obj->$method());
		}
		if($this->database->execute($query->toSQL())) {
			return true;
		}
		return false;
	}

	protected function getObjectFromRow($row) {
		$object = new \model\Accounting();
			$object->setId(\framework\utility\String::fromSQL($row->id));
			$object->setName(\framework\utility\String::fromSQL($row->name));
			$object->setDescription(\framework\utility\String::fromSQL($row->description));
			$object->setDate(\framework\utility\String::fromSQL($row->date));
			$object->setAmount(\framework\utility\String::fromSQL($row->amount));
			$object->setVat(\framework\utility\String::fromSQL($row->vat));
			$object->setIsChargeable(\framework\utility\String::fromSQL($row->is_chargeable));
			$object->setNature(\framework\utility\String::fromSQL($row->nature));
			$object->setAccountId(\framework\utility\String::fromSQL($row->account_id));
			$object->setProjectId(\framework\utility\String::fromSQL($row->project_id));
			$object->setCreatedDate(\framework\utility\String::fromSQL($row->created_date));
			$object->setUpdatedDate(\framework\utility\String::fromSQL($row->updated_date));

		$object->setNew(false);
		return $object;
	}

}
