<?php
/**
 * BaseWpkbPostmeta
 * Generated by Tyneo Base Tools
 *
 * @package     model
 * @author      Samuel Kauffmann <skauffmann@tyneo.net>
 * @copyright   Copyright (c) 2011, Samuel Kauffmann
 * @link        http://www.tyneo.net
 * @filesource	BaseWpkbPostmeta.class.php
 */
namespace model\base;

/**
 * This class provides an object representation of a WpkbPostmeta.
 *
 * @author		Samuel Kauffmann <skauffmann@tyneo.net>
 * @version		1.0
 */
abstract class BaseWpkbPostmeta extends AbstractBaseObject {


	/**
	 * Get the meta_id
	 *
	 * @return meta_id the meta_id value
	 */
	public function getMetaId() {
		return $this->properties->get('meta_id');
	}

	/**
	 * Set the meta_id
	 *
	 * @param meta_id the meta_id value
	 *
	 * @return BaseWpkbPostmeta
	 */
	public function setMetaId($meta_id) {
		$this->properties->set('meta_id', $meta_id);
		return $this;
	}


	/**
	 * Get the post_id
	 *
	 * @return post_id the post_id value
	 */
	public function getPostId() {
		return $this->properties->get('post_id');
	}

	/**
	 * Set the post_id
	 *
	 * @param post_id the post_id value
	 *
	 * @return BaseWpkbPostmeta
	 */
	public function setPostId($post_id) {
		$this->properties->set('post_id', $post_id);
		return $this;
	}


	/**
	 * Get the meta_key
	 *
	 * @return meta_key the meta_key value
	 */
	public function getMetaKey() {
		return $this->properties->get('meta_key');
	}

	/**
	 * Set the meta_key
	 *
	 * @param meta_key the meta_key value
	 *
	 * @return BaseWpkbPostmeta
	 */
	public function setMetaKey($meta_key) {
		$this->properties->set('meta_key', $meta_key);
		return $this;
	}


	/**
	 * Get the meta_value
	 *
	 * @return meta_value the meta_value value
	 */
	public function getMetaValue() {
		return $this->properties->get('meta_value');
	}

	/**
	 * Set the meta_value
	 *
	 * @param meta_value the meta_value value
	 *
	 * @return BaseWpkbPostmeta
	 */
	public function setMetaValue($meta_value) {
		$this->properties->set('meta_value', $meta_value);
		return $this;
	}

}
