<?php
/**
 * BaseUserManager
 * Generated by Tyneo Base Tools
 *
 * @package     model
 * @author      Samuel Kauffmann <skauffmann@tyneo.net>
 * @copyright   Copyright (c) 2011, Samuel Kauffmann
 * @link        http://www.tyneo.net
 * @filesource	BaseUserManager.class.php
 */
namespace model\base;

abstract class BaseUserManager extends AbstractBaseObjectManager {
	public function __construct(\framework\ApplicationContext $context) {
		parent::__construct($context);
		$this->setTableName('user');
	}

	public function getUsers() {
		$query = new \framework\query\QueryBuilder();
		$query->addSelect($this->getTableName().'.*');
		$query->addTable($this->getTableName());
		$results = $this->database->query($query->toSQL());
		return $this->getObjectsFromResult($results);
	}


	/**
	 * Returns a limited and filter number of Users	 *
	 * @param $start Number Index where we start to display Users (by default 0)
	 * @param $maxperpage Number Maximum number of item per page
	 * @param $filter String null or a User filter
	 */
	public function getLimitedUsers($start, $maxperpage, $filter) {
		if($maxperpage == null) $maxperpage = $this->context->getConfiguration()->get('max_per_page', 25);
		if($start == null) $start = 0;

		$query = new \framework\query\QueryBuilder();
		$query->addSelect($this->getTableName().'.*');
		$query->addTable($this->getTableName());

		if($filter != null) {
			$f = new \model\UserFilter($filter);
			$f->apply($query);
		}

		$query->setStart($start)->setMaxPerPage($maxperpage);

		$results = $this->database->query($query->toSQL());
		return $this->getObjectsFromResult($results);
	}

	public function countLimitedUsers($filter) {
		$query = new \framework\query\QueryBuilder();
		$query->addSelectCount($this->getTableName().'.id', 'total', true);
		$query->addTable($this->getTableName());

		if($filter != null) {
			$f = new \model\UserFilter($filter);
			$f->apply($query);
		}

		return $this->database->queryUniqueObject($query->toSQL())->total;
	}

	public function countUsers() {
		$query = new \framework\query\QueryBuilder();
		$query->addSelectCount($this->getTableName().'.id', 'total', true);
		$query->addTable($this->getTableName());
		return $this->database->queryUniqueObject($query->toSQL())->total;
	}

	public function getUser($id) {
		$query = new \framework\query\QueryBuilder();
		$query->addSelect($this->getTableName().'.*');
		$query->addTable($this->getTableName());
		if(!is_array($id)) {
			$query->addWhere($this->getTableName().'.id', \framework\query\operator\Operator::EQUAL, $id);
		} else {
			foreach ($id as $key => $value) {
				$query->addWhere($key, \framework\query\operator\Operator::EQUAL, $value);
			}
		}
		$object = $this->database->queryUniqueObject($query->toSQL());
		if($object != null) {
			return $this->getObjectFromRow($object);
		}
		return null;
	}

	protected function getUpdateQuery(\model\User $obj) {
		$query = new \framework\query\UpdateBuilder($this->getTableName());
					$query->setField('id', $obj->getId());
							$query->setField('password', $obj->getPassword());
							$query->setField('settings', $obj->getSettings());
							$query->setField('firstname', $obj->getFirstname());
							$query->setField('lastname', $obj->getLastname());
							$query->setField('email', $obj->getEmail());
							$query->setField('street', $obj->getStreet());
							$query->setField('zipcode', $obj->getZipcode());
							$query->setField('city', $obj->getCity());
							$query->setField('state', $obj->getState());
							$query->setField('country', $obj->getCountry());
							$query->setField('is_active', $obj->getIsActive());
							$query->setField('activation_code', $obj->getActivationCode());
							$query->setField('created_date', $obj->getCreatedDate());
							$query->setField('updated_date', 'CURDATE()', true);

		foreach ($this->getIdFields() as $id) {
			$method = 'get'.$this->slugify($id);
			$query->addWhere($id, \framework\query\operator\Operator::EQUAL, $obj->$method());
		}
		return $query;
	}

	protected function update(\model\User $obj) {
		$query = $this->getUpdateQuery($obj);
		return $this->database->execute($query->toSQL());
	}

	protected function getCreateQuery(\model\User $obj) {
		$query = new \framework\query\CreateBuilder($this->getTableName());
				$query->setField('id', $obj->getId());
					$query->setField('password', $obj->getPassword());
					$query->setField('settings', $obj->getSettings());
					$query->setField('firstname', $obj->getFirstname());
					$query->setField('lastname', $obj->getLastname());
					$query->setField('email', $obj->getEmail());
					$query->setField('street', $obj->getStreet());
					$query->setField('zipcode', $obj->getZipcode());
					$query->setField('city', $obj->getCity());
					$query->setField('state', $obj->getState());
					$query->setField('country', $obj->getCountry());
					$query->setField('is_active', $obj->getIsActive());
					$query->setField('activation_code', $obj->getActivationCode());
					$query->setField('created_date', 'CURDATE()', true);
					$query->setField('updated_date', 'CURDATE()', true);

		return $query;
	}

	protected function create(\model\User $obj) {
		$query = $this->getCreateQuery($obj);

		if($this->database->execute($query->toSQL())) {
			$obj->setNew(false);
			return true;
		}
		return false;
	}

	public function delete(\model\User $obj) {
		$query = new \framework\query\DeleteBuilder($this->getTableName());
		foreach ($this->getIdFields() as $id) {
			$method = 'get'.$this->slugify($id);
			$query->addWhere($id, \framework\query\operator\Operator::EQUAL, $obj->$method());
		}
		if($this->database->execute($query->toSQL())) {
			return true;
		}
		return false;
	}

	protected function getObjectFromRow($row) {
		$object = new \model\User();
			$object->setId(\framework\utility\String::fromSQL($row->id));
			$object->setPassword(\framework\utility\String::fromSQL($row->password));
			$object->setSettings(\framework\utility\String::fromSQL($row->settings));
			$object->setFirstname(\framework\utility\String::fromSQL($row->firstname));
			$object->setLastname(\framework\utility\String::fromSQL($row->lastname));
			$object->setEmail(\framework\utility\String::fromSQL($row->email));
			$object->setStreet(\framework\utility\String::fromSQL($row->street));
			$object->setZipcode(\framework\utility\String::fromSQL($row->zipcode));
			$object->setCity(\framework\utility\String::fromSQL($row->city));
			$object->setState(\framework\utility\String::fromSQL($row->state));
			$object->setCountry(\framework\utility\String::fromSQL($row->country));
			$object->setIsActive(\framework\utility\String::fromSQL($row->is_active));
			$object->setActivationCode(\framework\utility\String::fromSQL($row->activation_code));
			$object->setCreatedDate(\framework\utility\String::fromSQL($row->created_date));
			$object->setUpdatedDate(\framework\utility\String::fromSQL($row->updated_date));

		$object->setNew(false);
		return $object;
	}

}
