<?php
/**
 * BaseCompanyManager
 * Generated by Tyneo Base Tools
 *
 * @package     model
 * @author      Samuel Kauffmann <skauffmann@tyneo.net>
 * @copyright   Copyright (c) 2011, Samuel Kauffmann
 * @link        http://www.tyneo.net
 * @filesource	BaseCompanyManager.class.php
 */
namespace model\base;

abstract class BaseCompanyManager extends AbstractBaseObjectManager {
	public function __construct(\framework\ApplicationContext $context) {
		parent::__construct($context);
		$this->setTableName('company');
	}

	public function getCompanies() {
		$query = new \framework\query\QueryBuilder();
		$query->addSelect($this->getTableName().'.*');
		$query->addTable($this->getTableName());
		$results = $this->database->query($query->toSQL());
		return $this->getObjectsFromResult($results);
	}


	/**
	 * Returns a limited and filter number of Companies	 *
	 * @param $start Number Index where we start to display Companies (by default 0)
	 * @param $maxperpage Number Maximum number of item per page
	 * @param $filter String null or a Company filter
	 */
	public function getLimitedCompanies($start, $maxperpage, $filter) {
		if($maxperpage == null) $maxperpage = $this->context->getConfiguration()->get('max_per_page', 25);
		if($start == null) $start = 0;

		$query = new \framework\query\QueryBuilder();
		$query->addSelect($this->getTableName().'.*');
		$query->addTable($this->getTableName());

		if($filter != null) {
			$f = new \model\CompanyFilter($filter);
			$f->apply($query);
		}

		$query->setStart($start)->setMaxPerPage($maxperpage);

		$results = $this->database->query($query->toSQL());
		return $this->getObjectsFromResult($results);
	}

	public function countLimitedCompanies($filter) {
		$query = new \framework\query\QueryBuilder();
		$query->addSelectCount($this->getTableName().'.id', 'total', true);
		$query->addTable($this->getTableName());

		if($filter != null) {
			$f = new \model\CompanyFilter($filter);
			$f->apply($query);
		}

		return $this->database->queryUniqueObject($query->toSQL())->total;
	}

	public function countCompanies() {
		$query = new \framework\query\QueryBuilder();
		$query->addSelectCount($this->getTableName().'.id', 'total', true);
		$query->addTable($this->getTableName());
		return $this->database->queryUniqueObject($query->toSQL())->total;
	}

	public function getCompany($id) {
		$query = new \framework\query\QueryBuilder();
		$query->addSelect($this->getTableName().'.*');
		$query->addTable($this->getTableName());
		if(!is_array($id)) {
			$query->addWhere($this->getTableName().'.id', \framework\query\operator\Operator::EQUAL, $id);
		} else {
			foreach ($id as $key => $value) {
				$query->addWhere($key, \framework\query\operator\Operator::EQUAL, $value);
			}
		}
		$object = $this->database->queryUniqueObject($query->toSQL());
		if($object != null) {
			return $this->getObjectFromRow($object);
		}
		return null;
	}

	protected function getUpdateQuery(\model\Company $obj) {
		$query = new \framework\query\UpdateBuilder($this->getTableName());
					$query->setField('id', $obj->getId());
							$query->setField('name', $obj->getName());
							$query->setField('description', $obj->getDescription());
							$query->setField('address', $obj->getAddress());
							$query->setField('city', $obj->getCity());
							$query->setField('postal_code', $obj->getPostalCode());
							$query->setField('country', $obj->getCountry());
							$query->setField('tel', $obj->getTel());
							$query->setField('fax', $obj->getFax());
							$query->setField('website', $obj->getWebsite());
							$query->setField('vat_number', $obj->getVatNumber());
							$query->setField('contact_id', $obj->getContactId());
							$query->setField('langage', $obj->getLangage());
							$query->setField('created_date', $obj->getCreatedDate());
							$query->setField('updated_date', 'CURDATE()', true);

		foreach ($this->getIdFields() as $id) {
			$method = 'get'.$this->slugify($id);
			$query->addWhere($id, \framework\query\operator\Operator::EQUAL, $obj->$method());
		}
		return $query;
	}

	protected function update(\model\Company $obj) {
		$query = $this->getUpdateQuery($obj);
		return $this->database->execute($query->toSQL());
	}

	protected function getCreateQuery(\model\Company $obj) {
		$query = new \framework\query\CreateBuilder($this->getTableName());
				$query->setField('id', $obj->getId());
					$query->setField('name', $obj->getName());
					$query->setField('description', $obj->getDescription());
					$query->setField('address', $obj->getAddress());
					$query->setField('city', $obj->getCity());
					$query->setField('postal_code', $obj->getPostalCode());
					$query->setField('country', $obj->getCountry());
					$query->setField('tel', $obj->getTel());
					$query->setField('fax', $obj->getFax());
					$query->setField('website', $obj->getWebsite());
					$query->setField('vat_number', $obj->getVatNumber());
					$query->setField('contact_id', $obj->getContactId());
					$query->setField('langage', $obj->getLangage());
					$query->setField('created_date', 'CURDATE()', true);
					$query->setField('updated_date', 'CURDATE()', true);

		return $query;
	}

	protected function create(\model\Company $obj) {
		$query = $this->getCreateQuery($obj);

		if($this->database->execute($query->toSQL())) {
			$obj->setNew(false);
			return true;
		}
		return false;
	}

	public function delete(\model\Company $obj) {
		$query = new \framework\query\DeleteBuilder($this->getTableName());
		foreach ($this->getIdFields() as $id) {
			$method = 'get'.$this->slugify($id);
			$query->addWhere($id, \framework\query\operator\Operator::EQUAL, $obj->$method());
		}
		if($this->database->execute($query->toSQL())) {
			return true;
		}
		return false;
	}

	protected function getObjectFromRow($row) {
		$object = new \model\Company();
			$object->setId(\framework\utility\String::fromSQL($row->id));
			$object->setName(\framework\utility\String::fromSQL($row->name));
			$object->setDescription(\framework\utility\String::fromSQL($row->description));
			$object->setAddress(\framework\utility\String::fromSQL($row->address));
			$object->setCity(\framework\utility\String::fromSQL($row->city));
			$object->setPostalCode(\framework\utility\String::fromSQL($row->postal_code));
			$object->setCountry(\framework\utility\String::fromSQL($row->country));
			$object->setTel(\framework\utility\String::fromSQL($row->tel));
			$object->setFax(\framework\utility\String::fromSQL($row->fax));
			$object->setWebsite(\framework\utility\String::fromSQL($row->website));
			$object->setVatNumber(\framework\utility\String::fromSQL($row->vat_number));
			$object->setContactId(\framework\utility\String::fromSQL($row->contact_id));
			$object->setLangage(\framework\utility\String::fromSQL($row->langage));
			$object->setCreatedDate(\framework\utility\String::fromSQL($row->created_date));
			$object->setUpdatedDate(\framework\utility\String::fromSQL($row->updated_date));

		$object->setNew(false);
		return $object;
	}

}
