<?php
/**
 * BaseLinksManager
 * Generated by Tyneo Base Tools
 *
 * @package     model
 * @author      Samuel Kauffmann <skauffmann@tyneo.net>
 * @copyright   Copyright (c) 2011, Samuel Kauffmann
 * @link        http://www.tyneo.net
 * @filesource	BaseLinksManager.class.php
 */
namespace model\base;

abstract class BaseLinksManager extends AbstractBaseObjectManager {
	public function __construct(\framework\ApplicationContext $context) {
		parent::__construct($context);
		$this->setTableName('links');
	}

	public function getLinkss() {
		$query = new \framework\query\QueryBuilder();
		$query->addSelect($this->getTableName().'.*');
		$query->addTable($this->getTableName());
		$results = $this->database->query($query->toSQL());
		return $this->getObjectsFromResult($results);
	}

	public function getLinks($id) {
		$query = new \framework\query\QueryBuilder();
		$query->addSelect($this->getTableName().'.*');
		$query->addTable($this->getTableName());
		if(!is_array($id)) {
			$query->addWhere($this->getTableName().'.id', \framework\query\operator\Operator::EQUAL, $id);
		} else {
			foreach ($id as $key => $value) {
				$query->addWhere($key, \framework\query\operator\Operator::EQUAL, $value);
			}
		}
		$object = $this->database->queryUniqueObject($query->toSQL());
		if($object != null) {
			return $this->getObjectFromRow($object);
		}
		return null;
	}

	protected function getUpdateQuery(\model\Links $obj) {
		$query = new \framework\query\UpdateBuilder($this->getTableName());
					$query->setField('link_id', $obj->getLinkId());
							$query->setField('link_url', $obj->getLinkUrl());
							$query->setField('link_name', $obj->getLinkName());
							$query->setField('link_image', $obj->getLinkImage());
							$query->setField('link_target', $obj->getLinkTarget());
							$query->setField('link_description', $obj->getLinkDescription());
							$query->setField('link_visible', $obj->getLinkVisible());
							$query->setField('link_owner', $obj->getLinkOwner());
							$query->setField('link_rating', $obj->getLinkRating());
							$query->setField('link_updated', $obj->getLinkUpdated());
							$query->setField('link_rel', $obj->getLinkRel());
							$query->setField('link_notes', $obj->getLinkNotes());
							$query->setField('link_rss', $obj->getLinkRss());

		foreach ($this->getIdFields() as $id) {
			$method = 'get'.$this->slugify($id);
			$query->addWhere($id, \framework\query\operator\Operator::EQUAL, $obj->$method());
		}
		return $query;
	}

	protected function update(\model\Links $obj) {
		$query = $this->getUpdateQuery($obj);
		$this->database->execute($query->toSQL());
	}

	protected function getCreateQuery(\model\Links $obj) {
		$query = new \framework\query\CreateBuilder($this->getTableName());
				$query->setField('link_id', $obj->getLinkId());
					$query->setField('link_url', $obj->getLinkUrl());
					$query->setField('link_name', $obj->getLinkName());
					$query->setField('link_image', $obj->getLinkImage());
					$query->setField('link_target', $obj->getLinkTarget());
					$query->setField('link_description', $obj->getLinkDescription());
					$query->setField('link_visible', $obj->getLinkVisible());
					$query->setField('link_owner', $obj->getLinkOwner());
					$query->setField('link_rating', $obj->getLinkRating());
					$query->setField('link_updated', $obj->getLinkUpdated());
					$query->setField('link_rel', $obj->getLinkRel());
					$query->setField('link_notes', $obj->getLinkNotes());
					$query->setField('link_rss', $obj->getLinkRss());

		return $query;
	}

	protected function create(\model\Links $obj) {
		$query = $this->getCreateQuery($obj);
		$this->database->execute($query->toSQL());
		$obj->setNew(false);
	}

	protected function getObjectFromRow($row) {
		$object = new \model\Links();
			$object->setLinkId(\framework\utility\String::fromSQL($row->link_id));
			$object->setLinkUrl(\framework\utility\String::fromSQL($row->link_url));
			$object->setLinkName(\framework\utility\String::fromSQL($row->link_name));
			$object->setLinkImage(\framework\utility\String::fromSQL($row->link_image));
			$object->setLinkTarget(\framework\utility\String::fromSQL($row->link_target));
			$object->setLinkDescription(\framework\utility\String::fromSQL($row->link_description));
			$object->setLinkVisible(\framework\utility\String::fromSQL($row->link_visible));
			$object->setLinkOwner(\framework\utility\String::fromSQL($row->link_owner));
			$object->setLinkRating(\framework\utility\String::fromSQL($row->link_rating));
			$object->setLinkUpdated(\framework\utility\String::fromSQL($row->link_updated));
			$object->setLinkRel(\framework\utility\String::fromSQL($row->link_rel));
			$object->setLinkNotes(\framework\utility\String::fromSQL($row->link_notes));
			$object->setLinkRss(\framework\utility\String::fromSQL($row->link_rss));

		$object->setNew(false);
		return $object;
	}

}
