<?php
/**
 * BaseEvent
 * Generated by Tyneo Base Tools
 *
 * @package     model
 * @author      Samuel Kauffmann <skauffmann@tyneo.net>
 * @copyright   Copyright (c) 2011, Samuel Kauffmann
 * @link        http://www.tyneo.net
 * @filesource	BaseEvent.class.php
 */
namespace model\base;

/**
 * This class provides an object representation of a Event.
 *
 * @author		Samuel Kauffmann <skauffmann@tyneo.net>
 * @version		1.0
 */
abstract class BaseEvent extends AbstractBaseObject {


	/**
	 * Get the id
	 *
	 * @return id the id value
	 */
	public function getId() {
		return $this->properties->get('id');
	}

	/**
	 * Set the id
	 *
	 * @param id the id value
	 *
	 * @return BaseEvent
	 */
	public function setId($id) {
		$this->properties->set('id', $id);
		return $this;
	}


	/**
	 * Get the name
	 *
	 * @return name the name value
	 */
	public function getName() {
		return $this->properties->get('name');
	}

	/**
	 * Set the name
	 *
	 * @param name the name value
	 *
	 * @return BaseEvent
	 */
	public function setName($name) {
		$this->properties->set('name', $name);
		return $this;
	}


	/**
	 * Get the date
	 *
	 * @return date the date value
	 */
	public function getDate() {
		return $this->properties->get('date');
	}

	/**
	 * Set the date
	 *
	 * @param date the date value
	 *
	 * @return BaseEvent
	 */
	public function setDate($date) {
		$this->properties->set('date', $date);
		return $this;
	}


	/**
	 * Get the location
	 *
	 * @return location the location value
	 */
	public function getLocation() {
		return $this->properties->get('location');
	}

	/**
	 * Set the location
	 *
	 * @param location the location value
	 *
	 * @return BaseEvent
	 */
	public function setLocation($location) {
		$this->properties->set('location', $location);
		return $this;
	}


	/**
	 * Get the description
	 *
	 * @return description the description value
	 */
	public function getDescription() {
		return $this->properties->get('description');
	}

	/**
	 * Set the description
	 *
	 * @param description the description value
	 *
	 * @return BaseEvent
	 */
	public function setDescription($description) {
		$this->properties->set('description', $description);
		return $this;
	}


	/**
	 * Get the picture
	 *
	 * @return picture the picture value
	 */
	public function getPicture() {
		return $this->properties->get('picture');
	}

	/**
	 * Set the picture
	 *
	 * @param picture the picture value
	 *
	 * @return BaseEvent
	 */
	public function setPicture($picture) {
		$this->properties->set('picture', $picture);
		return $this;
	}


	/**
	 * Get the state
	 *
	 * @return state the state value
	 */
	public function getState() {
		return $this->properties->get('state');
	}

	/**
	 * Set the state
	 *
	 * @param state the state value
	 *
	 * @return BaseEvent
	 */
	public function setState($state) {
		$this->properties->set('state', $state);
		return $this;
	}


	public function __toString() {
				return $this->getName();
    }



}
