<?php
/**
 * BaseUser
 * Generated by Tyneo Base Tools
 *
 * @package     model
 * @author      Samuel Kauffmann <skauffmann@tyneo.net>
 * @copyright   Copyright (c) 2011, Samuel Kauffmann
 * @link        http://www.tyneo.net
 * @filesource	BaseUser.class.php
 */
namespace model\base;

/**
 * This class provides an object representation of a User.
 *
 * @author		Samuel Kauffmann <skauffmann@tyneo.net>
 * @version		1.0
 */
abstract class BaseUser extends AbstractBaseObject {


	/**
	 * Get the id
	 *
	 * @return id the id value
	 */
	public function getId() {
		return $this->properties->get('id');
	}

	/**
	 * Set the id
	 *
	 * @param id the id value
	 *
	 * @return BaseUser
	 */
	public function setId($id) {
		$this->properties->set('id', $id);
		return $this;
	}


	/**
	 * Get the password
	 *
	 * @return password the password value
	 */
	public function getPassword() {
		return $this->properties->get('password');
	}

	/**
	 * Set the password
	 *
	 * @param password the password value
	 *
	 * @return BaseUser
	 */
	public function setPassword($password) {
		$this->properties->set('password', $password);
		return $this;
	}


	/**
	 * Get the settings
	 *
	 * @return settings the settings value
	 */
	public function getSettings() {
		return $this->properties->get('settings');
	}

	/**
	 * Set the settings
	 *
	 * @param settings the settings value
	 *
	 * @return BaseUser
	 */
	public function setSettings($settings) {
		$this->properties->set('settings', $settings);
		return $this;
	}


	/**
	 * Get the firstname
	 *
	 * @return firstname the firstname value
	 */
	public function getFirstname() {
		return $this->properties->get('firstname');
	}

	/**
	 * Set the firstname
	 *
	 * @param firstname the firstname value
	 *
	 * @return BaseUser
	 */
	public function setFirstname($firstname) {
		$this->properties->set('firstname', $firstname);
		return $this;
	}


	/**
	 * Get the lastname
	 *
	 * @return lastname the lastname value
	 */
	public function getLastname() {
		return $this->properties->get('lastname');
	}

	/**
	 * Set the lastname
	 *
	 * @param lastname the lastname value
	 *
	 * @return BaseUser
	 */
	public function setLastname($lastname) {
		$this->properties->set('lastname', $lastname);
		return $this;
	}


	/**
	 * Get the email
	 *
	 * @return email the email value
	 */
	public function getEmail() {
		return $this->properties->get('email');
	}

	/**
	 * Set the email
	 *
	 * @param email the email value
	 *
	 * @return BaseUser
	 */
	public function setEmail($email) {
		$this->properties->set('email', $email);
		return $this;
	}


	/**
	 * Get the street
	 *
	 * @return street the street value
	 */
	public function getStreet() {
		return $this->properties->get('street');
	}

	/**
	 * Set the street
	 *
	 * @param street the street value
	 *
	 * @return BaseUser
	 */
	public function setStreet($street) {
		$this->properties->set('street', $street);
		return $this;
	}


	/**
	 * Get the zipcode
	 *
	 * @return zipcode the zipcode value
	 */
	public function getZipcode() {
		return $this->properties->get('zipcode');
	}

	/**
	 * Set the zipcode
	 *
	 * @param zipcode the zipcode value
	 *
	 * @return BaseUser
	 */
	public function setZipcode($zipcode) {
		$this->properties->set('zipcode', $zipcode);
		return $this;
	}


	/**
	 * Get the city
	 *
	 * @return city the city value
	 */
	public function getCity() {
		return $this->properties->get('city');
	}

	/**
	 * Set the city
	 *
	 * @param city the city value
	 *
	 * @return BaseUser
	 */
	public function setCity($city) {
		$this->properties->set('city', $city);
		return $this;
	}


	/**
	 * Get the state
	 *
	 * @return state the state value
	 */
	public function getState() {
		return $this->properties->get('state');
	}

	/**
	 * Set the state
	 *
	 * @param state the state value
	 *
	 * @return BaseUser
	 */
	public function setState($state) {
		$this->properties->set('state', $state);
		return $this;
	}


	/**
	 * Get the country
	 *
	 * @return country the country value
	 */
	public function getCountry() {
		return $this->properties->get('country');
	}

	/**
	 * Set the country
	 *
	 * @param country the country value
	 *
	 * @return BaseUser
	 */
	public function setCountry($country) {
		$this->properties->set('country', $country);
		return $this;
	}


	/**
	 * Get the is_active
	 *
	 * @return is_active the is_active value
	 */
	public function getIsActive() {
		return $this->properties->get('is_active');
	}

	/**
	 * Set the is_active
	 *
	 * @param is_active the is_active value
	 *
	 * @return BaseUser
	 */
	public function setIsActive($is_active) {
		$this->properties->set('is_active', $is_active);
		return $this;
	}


	/**
	 * Get the activation_code
	 *
	 * @return activation_code the activation_code value
	 */
	public function getActivationCode() {
		return $this->properties->get('activation_code');
	}

	/**
	 * Set the activation_code
	 *
	 * @param activation_code the activation_code value
	 *
	 * @return BaseUser
	 */
	public function setActivationCode($activation_code) {
		$this->properties->set('activation_code', $activation_code);
		return $this;
	}


	public function __toString() {
				return $this->getId();
    }



}
