<?php
/**
 * BaseUsermetaManager
 * Generated by Tyneo Base Tools
 *
 * @package     model
 * @author      Samuel Kauffmann <skauffmann@tyneo.net>
 * @copyright   Copyright (c) 2011, Samuel Kauffmann
 * @link        http://www.tyneo.net
 * @filesource	BaseUsermetaManager.class.php
 */
namespace model\base;

abstract class BaseUsermetaManager extends AbstractBaseObjectManager {
	public function __construct(\framework\ApplicationContext $context) {
		parent::__construct($context);
		$this->setTableName('usermeta');
	}

	public function getUsermetas() {
		$query = new \framework\query\QueryBuilder();
		$query->addSelect($this->getTableName().'.*');
		$query->addTable($this->getTableName());
		$results = $this->database->query($query->toSQL());
		return $this->getObjectsFromResult($results);
	}

	public function getUsermeta($id) {
		$query = new \framework\query\QueryBuilder();
		$query->addSelect($this->getTableName().'.*');
		$query->addTable($this->getTableName());
		if(!is_array($id)) {
			$query->addWhere($this->getTableName().'.id', \framework\query\operator\Operator::EQUAL, $id);
		} else {
			foreach ($id as $key => $value) {
				$query->addWhere($key, \framework\query\operator\Operator::EQUAL, $value);
			}
		}
		$object = $this->database->queryUniqueObject($query->toSQL());
		if($object != null) {
			return $this->getObjectFromRow($object);
		}
		return null;
	}

	protected function getUpdateQuery(\model\Usermeta $obj) {
		$query = new \framework\query\UpdateBuilder($this->getTableName());
					$query->setField('umeta_id', $obj->getUmetaId());
							$query->setField('user_id', $obj->getUserId());
							$query->setField('meta_key', $obj->getMetaKey());
							$query->setField('meta_value', $obj->getMetaValue());

		foreach ($this->getIdFields() as $id) {
			$method = 'get'.$this->slugify($id);
			$query->addWhere($id, \framework\query\operator\Operator::EQUAL, $obj->$method());
		}
		return $query;
	}

	protected function update(\model\Usermeta $obj) {
		$query = $this->getUpdateQuery($obj);
		$this->database->execute($query->toSQL());
	}

	protected function getCreateQuery(\model\Usermeta $obj) {
		$query = new \framework\query\CreateBuilder($this->getTableName());
				$query->setField('umeta_id', $obj->getUmetaId());
					$query->setField('user_id', $obj->getUserId());
					$query->setField('meta_key', $obj->getMetaKey());
					$query->setField('meta_value', $obj->getMetaValue());

		return $query;
	}

	protected function create(\model\Usermeta $obj) {
		$query = $this->getCreateQuery($obj);
		$this->database->execute($query->toSQL());
		$obj->setNew(false);
	}

	protected function getObjectFromRow($row) {
		$object = new \model\Usermeta();
			$object->setUmetaId(\framework\utility\String::fromSQL($row->umeta_id));
			$object->setUserId(\framework\utility\String::fromSQL($row->user_id));
			$object->setMetaKey(\framework\utility\String::fromSQL($row->meta_key));
			$object->setMetaValue(\framework\utility\String::fromSQL($row->meta_value));

		$object->setNew(false);
		return $object;
	}

}
