<?php
/**
 * BaseContactManager
 * Generated by Tyneo Base Tools
 *
 * @package     model
 * @author      Samuel Kauffmann <skauffmann@tyneo.net>
 * @copyright   Copyright (c) 2011, Samuel Kauffmann
 * @link        http://www.tyneo.net
 * @filesource	BaseContactManager.class.php
 */
namespace model\base;

abstract class BaseContactManager extends AbstractBaseObjectManager {
	public function __construct(\framework\ApplicationContext $context) {
		parent::__construct($context);
		$this->setTableName('contact');
	}

	public function getContacts() {
		$query = new \framework\query\QueryBuilder();
		$query->addSelect($this->getTableName().'.*');
		$query->addTable($this->getTableName());
		$results = $this->database->query($query->toSQL());
		return $this->getObjectsFromResult($results);
	}


	/**
	 * Returns a limited and filter number of Contacts	 *
	 * @param $start Number Index where we start to display Contacts (by default 0)
	 * @param $maxperpage Number Maximum number of item per page
	 * @param $filter String null or a Contact filter
	 */
	public function getLimitedContacts($start, $maxperpage, $filter) {
		if($maxperpage == null) $maxperpage = $this->context->getConfiguration()->get('max_per_page', 25);
		if($start == null) $start = 0;

		$query = new \framework\query\QueryBuilder();
		$query->addSelect($this->getTableName().'.*');
		$query->addTable($this->getTableName());

		if($filter != null) {
			$f = new \model\ContactFilter($filter);
			$f->apply($query);
		}

		$query->setStart($start)->setMaxPerPage($maxperpage);

		$results = $this->database->query($query->toSQL());
		return $this->getObjectsFromResult($results);
	}

	public function countLimitedContacts($filter) {
		$query = new \framework\query\QueryBuilder();
		$query->addSelectCount($this->getTableName().'.id', 'total', true);
		$query->addTable($this->getTableName());

		if($filter != null) {
			$f = new \model\ContactFilter($filter);
			$f->apply($query);
		}

		return $this->database->queryUniqueObject($query->toSQL())->total;
	}

	public function countContacts() {
		$query = new \framework\query\QueryBuilder();
		$query->addSelectCount($this->getTableName().'.id', 'total', true);
		$query->addTable($this->getTableName());
		return $this->database->queryUniqueObject($query->toSQL())->total;
	}

	public function getContact($id) {
		$query = new \framework\query\QueryBuilder();
		$query->addSelect($this->getTableName().'.*');
		$query->addTable($this->getTableName());
		if(!is_array($id)) {
			$query->addWhere($this->getTableName().'.id', \framework\query\operator\Operator::EQUAL, $id);
		} else {
			foreach ($id as $key => $value) {
				$query->addWhere($key, \framework\query\operator\Operator::EQUAL, $value);
			}
		}
		$object = $this->database->queryUniqueObject($query->toSQL());
		if($object != null) {
			return $this->getObjectFromRow($object);
		}
		return null;
	}

	protected function getUpdateQuery(\model\Contact $obj) {
		$query = new \framework\query\UpdateBuilder($this->getTableName());
					$query->setField('id', $obj->getId());
							$query->setField('firstname', $obj->getFirstname());
							$query->setField('lastname', $obj->getLastname());
							$query->setField('email', $obj->getEmail());
							$query->setField('mob', $obj->getMob());
							$query->setField('tel', $obj->getTel());
							$query->setField('fax', $obj->getFax());
							$query->setField('comment', $obj->getComment());
							$query->setField('company_id', $obj->getCompanyId());
							$query->setField('created_date', $obj->getCreatedDate());
							$query->setField('updated_date', 'CURDATE()', true);

		foreach ($this->getIdFields() as $id) {
			$method = 'get'.$this->slugify($id);
			$query->addWhere($id, \framework\query\operator\Operator::EQUAL, $obj->$method());
		}
		return $query;
	}

	protected function update(\model\Contact $obj) {
		$query = $this->getUpdateQuery($obj);
		return $this->database->execute($query->toSQL());
	}

	protected function getCreateQuery(\model\Contact $obj) {
		$query = new \framework\query\CreateBuilder($this->getTableName());
				$query->setField('id', $obj->getId());
					$query->setField('firstname', $obj->getFirstname());
					$query->setField('lastname', $obj->getLastname());
					$query->setField('email', $obj->getEmail());
					$query->setField('mob', $obj->getMob());
					$query->setField('tel', $obj->getTel());
					$query->setField('fax', $obj->getFax());
					$query->setField('comment', $obj->getComment());
					$query->setField('company_id', $obj->getCompanyId());
					$query->setField('created_date', 'CURDATE()', true);
					$query->setField('updated_date', 'CURDATE()', true);

		return $query;
	}

	protected function create(\model\Contact $obj) {
		$query = $this->getCreateQuery($obj);

		if($this->database->execute($query->toSQL())) {
			$obj->setNew(false);
			return true;
		}
		return false;
	}

	public function delete(\model\Contact $obj) {
		$query = new \framework\query\DeleteBuilder($this->getTableName());
		foreach ($this->getIdFields() as $id) {
			$method = 'get'.$this->slugify($id);
			$query->addWhere($id, \framework\query\operator\Operator::EQUAL, $obj->$method());
		}
		if($this->database->execute($query->toSQL())) {
			return true;
		}
		return false;
	}

	protected function getObjectFromRow($row) {
		$object = new \model\Contact();
			$object->setId(\framework\utility\String::fromSQL($row->id));
			$object->setFirstname(\framework\utility\String::fromSQL($row->firstname));
			$object->setLastname(\framework\utility\String::fromSQL($row->lastname));
			$object->setEmail(\framework\utility\String::fromSQL($row->email));
			$object->setMob(\framework\utility\String::fromSQL($row->mob));
			$object->setTel(\framework\utility\String::fromSQL($row->tel));
			$object->setFax(\framework\utility\String::fromSQL($row->fax));
			$object->setComment(\framework\utility\String::fromSQL($row->comment));
			$object->setCompanyId(\framework\utility\String::fromSQL($row->company_id));
			$object->setCreatedDate(\framework\utility\String::fromSQL($row->created_date));
			$object->setUpdatedDate(\framework\utility\String::fromSQL($row->updated_date));

		$object->setNew(false);
		return $object;
	}

}
