<?php
/**
 * BaseMailinglistManager
 * Generated by Tyneo Base Tools
 *
 * @package     model
 * @author      Samuel Kauffmann <skauffmann@tyneo.net>
 * @copyright   Copyright (c) 2011, Samuel Kauffmann
 * @link        http://www.tyneo.net
 * @filesource	BaseMailinglistManager.class.php
 */
namespace model\base;

abstract class BaseMailinglistManager extends AbstractBaseObjectManager {
	public function __construct(\framework\ApplicationContext $context) {
		parent::__construct($context);
		$this->setTableName('mailing_list');
	}

	public function getMailinglists() {
		$query = new \framework\query\QueryBuilder();
		$query->addSelect($this->getTableName().'.*');
		$query->addTable($this->getTableName());
		$results = $this->database->query($query->toSQL());
		return $this->getObjectsFromResult($results);
	}


	/**
	 * Returns a limited and filter number of Mailinglists	 *
	 * @param $start Number Index where we start to display Mailinglists (by default 0)
	 * @param $maxperpage Number Maximum number of item per page
	 * @param $filter String null or a Mailinglist filter
	 */
	public function getLimitedMailinglists($start, $maxperpage, $filter) {
		if($maxperpage == null) $maxperpage = $this->context->getConfiguration()->get('max_per_page', 25);
		if($start == null) $start = 0;

		$query = new \framework\query\QueryBuilder();
		$query->addSelect($this->getTableName().'.*');
		$query->addTable($this->getTableName());

		if($filter != null) {
			$f = new \model\MailinglistFilter($filter);
			$f->apply($query);
		}

		$query->setStart($start)->setMaxPerPage($maxperpage);

		$results = $this->database->query($query->toSQL());
		return $this->getObjectsFromResult($results);
	}

	public function countLimitedMailinglists($filter) {
		$query = new \framework\query\QueryBuilder();
		$query->addSelectCount($this->getTableName().'.id', 'total', true);
		$query->addTable($this->getTableName());

		if($filter != null) {
			$f = new \model\MailinglistFilter($filter);
			$f->apply($query);
		}

		return $this->database->queryUniqueObject($query->toSQL())->total;
	}

	public function countMailinglists() {
		$query = new \framework\query\QueryBuilder();
		$query->addSelectCount($this->getTableName().'.id', 'total', true);
		$query->addTable($this->getTableName());
		return $this->database->queryUniqueObject($query->toSQL())->total;
	}

	public function getMailinglist($id) {
		$query = new \framework\query\QueryBuilder();
		$query->addSelect($this->getTableName().'.*');
		$query->addTable($this->getTableName());
		if(!is_array($id)) {
			$query->addWhere($this->getTableName().'.id', \framework\query\operator\Operator::EQUAL, $id);
		} else {
			foreach ($id as $key => $value) {
				$query->addWhere($key, \framework\query\operator\Operator::EQUAL, $value);
			}
		}
		$object = $this->database->queryUniqueObject($query->toSQL());
		if($object != null) {
			return $this->getObjectFromRow($object);
		}
		return null;
	}

	protected function getUpdateQuery(\model\Mailinglist $obj) {
		$query = new \framework\query\UpdateBuilder($this->getTableName());
					$query->setField('id', $obj->getId());
							$query->setField('mail', $obj->getMail());
							$query->setField('state', $obj->getState());
							$query->setField('firstname', $obj->getFirstname());
							$query->setField('lastname', $obj->getLastname());
							$query->setField('company', $obj->getCompany());
							$query->setField('position', $obj->getPosition());
							$query->setField('interest', $obj->getInterest());
							$query->setField('activation_code', $obj->getActivationCode());
							$query->setField('created_date', $obj->getCreatedDate());
							$query->setField('updated_date', 'CURDATE()', true);

		foreach ($this->getIdFields() as $id) {
			$method = 'get'.$this->slugify($id);
			$query->addWhere($id, \framework\query\operator\Operator::EQUAL, $obj->$method());
		}
		return $query;
	}

	protected function update(\model\Mailinglist $obj) {
		$query = $this->getUpdateQuery($obj);
		return $this->database->execute($query->toSQL());
	}

	protected function getCreateQuery(\model\Mailinglist $obj) {
		$query = new \framework\query\CreateBuilder($this->getTableName());
				$query->setField('id', $obj->getId());
					$query->setField('mail', $obj->getMail());
					$query->setField('state', $obj->getState());
					$query->setField('firstname', $obj->getFirstname());
					$query->setField('lastname', $obj->getLastname());
					$query->setField('company', $obj->getCompany());
					$query->setField('position', $obj->getPosition());
					$query->setField('interest', $obj->getInterest());
					$query->setField('activation_code', $obj->getActivationCode());
					$query->setField('created_date', 'CURDATE()', true);
					$query->setField('updated_date', 'CURDATE()', true);

		return $query;
	}

	protected function create(\model\Mailinglist $obj) {
		$query = $this->getCreateQuery($obj);

		if($this->database->execute($query->toSQL())) {
			$obj->setNew(false);
			return true;
		}
		return false;
	}

	public function delete(\model\Mailinglist $obj) {
		$query = new \framework\query\DeleteBuilder($this->getTableName());
		foreach ($this->getIdFields() as $id) {
			$method = 'get'.$this->slugify($id);
			$query->addWhere($id, \framework\query\operator\Operator::EQUAL, $obj->$method());
		}
		if($this->database->execute($query->toSQL())) {
			return true;
		}
		return false;
	}

	protected function getObjectFromRow($row) {
		$object = new \model\Mailinglist();
			$object->setId(\framework\utility\String::fromSQL($row->id));
			$object->setMail(\framework\utility\String::fromSQL($row->mail));
			$object->setState(\framework\utility\String::fromSQL($row->state));
			$object->setFirstname(\framework\utility\String::fromSQL($row->firstname));
			$object->setLastname(\framework\utility\String::fromSQL($row->lastname));
			$object->setCompany(\framework\utility\String::fromSQL($row->company));
			$object->setPosition(\framework\utility\String::fromSQL($row->position));
			$object->setInterest(\framework\utility\String::fromSQL($row->interest));
			$object->setActivationCode(\framework\utility\String::fromSQL($row->activation_code));
			$object->setCreatedDate(\framework\utility\String::fromSQL($row->created_date));
			$object->setUpdatedDate(\framework\utility\String::fromSQL($row->updated_date));

		$object->setNew(false);
		return $object;
	}

}
