<?php
/**
 * BaseToolManager
 * Generated by Tyneo Base Tools
 *
 * @package     model
 * @author      Samuel Kauffmann <skauffmann@tyneo.net>
 * @copyright   Copyright (c) 2011, Samuel Kauffmann
 * @link        http://www.tyneo.net
 * @filesource	BaseToolManager.class.php
 */
namespace model\base;

abstract class BaseToolManager extends AbstractBaseObjectManager {
	public function __construct(\framework\ApplicationContext $context) {
		parent::__construct($context);
		$this->setTableName('tool');
	}

	public function getTools() {
		$query = new \framework\query\QueryBuilder();
		$query->addSelect($this->getTableName().'.*');
		$query->addTable($this->getTableName());
		$results = $this->database->query($query->toSQL());
		return $this->getObjectsFromResult($results);
	}


	/**
	 * Returns a limited and filter number of Tools	 *
	 * @param $start Number Index where we start to display Tools (by default 0)
	 * @param $maxperpage Number Maximum number of item per page
	 * @param $filter String null or a Tool filter
	 */
	public function getLimitedTools($start, $maxperpage, $filter) {
		if($maxperpage == null) $maxperpage = $this->context->getConfiguration()->get('max_per_page', 25);
		if($start == null) $start = 0;

		$query = new \framework\query\QueryBuilder();
		$query->addSelect($this->getTableName().'.*');
		$query->addTable($this->getTableName());

		if($filter != null) {
			$f = new \model\ToolFilter($filter);
			$f->apply($query);
		}

		$query->setStart($start)->setMaxPerPage($maxperpage);

		$results = $this->database->query($query->toSQL());
		return $this->getObjectsFromResult($results);
	}

	public function countLimitedTools($filter) {
		$query = new \framework\query\QueryBuilder();
		$query->addSelectCount($this->getTableName().'.id', 'total', true);
		$query->addTable($this->getTableName());

		if($filter != null) {
			$f = new \model\ToolFilter($filter);
			$f->apply($query);
		}

		return $this->database->queryUniqueObject($query->toSQL())->total;
	}

	public function countTools() {
		$query = new \framework\query\QueryBuilder();
		$query->addSelectCount($this->getTableName().'.id', 'total', true);
		$query->addTable($this->getTableName());
		return $this->database->queryUniqueObject($query->toSQL())->total;
	}

	public function getTool($id) {
		$query = new \framework\query\QueryBuilder();
		$query->addSelect($this->getTableName().'.*');
		$query->addTable($this->getTableName());
		if(!is_array($id)) {
			$query->addWhere($this->getTableName().'.id', \framework\query\operator\Operator::EQUAL, $id);
		} else {
			foreach ($id as $key => $value) {
				$query->addWhere($key, \framework\query\operator\Operator::EQUAL, $value);
			}
		}
		$object = $this->database->queryUniqueObject($query->toSQL());
		if($object != null) {
			return $this->getObjectFromRow($object);
		}
		return null;
	}

	protected function getUpdateQuery(\model\Tool $obj) {
		$query = new \framework\query\UpdateBuilder($this->getTableName());
					$query->setField('id', $obj->getId());
							$query->setField('name', $obj->getName());
							$query->setField('slug', $obj->getSlug());
							$query->setField('img', $obj->getImg());
							$query->setField('version', $obj->getVersion());
							$query->setField('description', $obj->getDescription());
							$query->setField('environment', $obj->getEnvironment());
							$query->setField('license', $obj->getLicense());
							$query->setField('tool_type_id', $obj->getToolTypeId());
							$query->setField('editor_id', $obj->getEditorId());

		foreach ($this->getIdFields() as $id) {
			$method = 'get'.$this->slugify($id);
			$query->addWhere($id, \framework\query\operator\Operator::EQUAL, $obj->$method());
		}
		return $query;
	}

	protected function update(\model\Tool $obj) {
		$query = $this->getUpdateQuery($obj);
		return $this->database->execute($query->toSQL());
	}

	protected function getCreateQuery(\model\Tool $obj) {
		$query = new \framework\query\CreateBuilder($this->getTableName());
				$query->setField('id', $obj->getId());
					$query->setField('name', $obj->getName());
					$query->setField('slug', $obj->getSlug());
					$query->setField('img', $obj->getImg());
					$query->setField('version', $obj->getVersion());
					$query->setField('description', $obj->getDescription());
					$query->setField('environment', $obj->getEnvironment());
					$query->setField('license', $obj->getLicense());
					$query->setField('tool_type_id', $obj->getToolTypeId());
					$query->setField('editor_id', $obj->getEditorId());

		return $query;
	}

	protected function create(\model\Tool $obj) {
		$query = $this->getCreateQuery($obj);

		if($this->database->execute($query->toSQL())) {
			$obj->setNew(false);
			return true;
		}
		return false;
	}

	public function delete(\model\Tool $obj) {
		$query = new \framework\query\DeleteBuilder($this->getTableName());
		foreach ($this->getIdFields() as $id) {
			$method = 'get'.$this->slugify($id);
			$query->addWhere($id, \framework\query\operator\Operator::EQUAL, $obj->$method());
		}
		if($this->database->execute($query->toSQL())) {
			return true;
		}
		return false;
	}

	protected function getObjectFromRow($row) {
		$object = new \model\Tool();
			$object->setId(\framework\utility\String::fromSQL($row->id));
			$object->setName(\framework\utility\String::fromSQL($row->name));
			$object->setSlug(\framework\utility\String::fromSQL($row->slug));
			$object->setImg(\framework\utility\String::fromSQL($row->img));
			$object->setVersion(\framework\utility\String::fromSQL($row->version));
			$object->setDescription(\framework\utility\String::fromSQL($row->description));
			$object->setEnvironment(\framework\utility\String::fromSQL($row->environment));
			$object->setLicense(\framework\utility\String::fromSQL($row->license));
			$object->setToolTypeId(\framework\utility\String::fromSQL($row->tool_type_id));
			$object->setEditorId(\framework\utility\String::fromSQL($row->editor_id));

		$object->setNew(false);
		return $object;
	}

}
