<?php
/**
 * BaseContract
 * Generated by Tyneo Base Tools
 *
 * @package     model
 * @author      Samuel Kauffmann <skauffmann@tyneo.net>
 * @copyright   Copyright (c) 2011, Samuel Kauffmann
 * @link        http://www.tyneo.net
 * @filesource	BaseContract.class.php
 */
namespace model\base;

/**
 * This class provides an object representation of a Contract.
 *
 * @author		Samuel Kauffmann <skauffmann@tyneo.net>
 * @version		1.0
 */
abstract class BaseContract extends AbstractBaseObject {


	/**
	 * Get the id
	 *
	 * @return id the id value
	 */
	public function getId() {
		return $this->properties->get('id');
	}

	/**
	 * Set the id
	 *
	 * @param id the id value
	 *
	 * @return BaseContract
	 */
	public function setId($id) {
		$this->properties->set('id', $id);
		return $this;
	}


	/**
	 * Get the name
	 *
	 * @return name the name value
	 */
	public function getName() {
		return $this->properties->get('name');
	}

	/**
	 * Set the name
	 *
	 * @param name the name value
	 *
	 * @return BaseContract
	 */
	public function setName($name) {
		$this->properties->set('name', $name);
		return $this;
	}


	/**
	 * Get the ext_name
	 *
	 * @return ext_name the ext_name value
	 */
	public function getExtName() {
		return $this->properties->get('ext_name');
	}

	/**
	 * Set the ext_name
	 *
	 * @param ext_name the ext_name value
	 *
	 * @return BaseContract
	 */
	public function setExtName($ext_name) {
		$this->properties->set('ext_name', $ext_name);
		return $this;
	}


	/**
	 * Get the start_date
	 *
	 * @return start_date the start_date value
	 */
	public function getStartDate() {
		return $this->properties->get('start_date');
	}

	/**
	 * Set the start_date
	 *
	 * @param start_date the start_date value
	 *
	 * @return BaseContract
	 */
	public function setStartDate($start_date) {
		$this->properties->set('start_date', $start_date);
		return $this;
	}


	/**
	 * Get the end_date
	 *
	 * @return end_date the end_date value
	 */
	public function getEndDate() {
		return $this->properties->get('end_date');
	}

	/**
	 * Set the end_date
	 *
	 * @param end_date the end_date value
	 *
	 * @return BaseContract
	 */
	public function setEndDate($end_date) {
		$this->properties->set('end_date', $end_date);
		return $this;
	}


	/**
	 * Get the comment
	 *
	 * @return comment the comment value
	 */
	public function getComment() {
		return $this->properties->get('comment');
	}

	/**
	 * Set the comment
	 *
	 * @param comment the comment value
	 *
	 * @return BaseContract
	 */
	public function setComment($comment) {
		$this->properties->set('comment', $comment);
		return $this;
	}


	/**
	 * Get the company_id
	 *
	 * @return company_id the company_id value
	 */
	public function getCompanyId() {
		return $this->properties->get('company_id');
	}

	/**
	 * Set the company_id
	 *
	 * @param company_id the company_id value
	 *
	 * @return BaseContract
	 */
	public function setCompanyId($company_id) {
		$this->properties->set('company_id', $company_id);
		return $this;
	}


	/**
	 * Get the project_id
	 *
	 * @return project_id the project_id value
	 */
	public function getProjectId() {
		return $this->properties->get('project_id');
	}

	/**
	 * Set the project_id
	 *
	 * @param project_id the project_id value
	 *
	 * @return BaseContract
	 */
	public function setProjectId($project_id) {
		$this->properties->set('project_id', $project_id);
		return $this;
	}


	public function __toString() {
				return $this->getName();
    }



	public function getCompany() {
		$companyManager = new \model\CompanyManager();
		return $companyManager->getCompany($this->getCompanyId());
	}

	public function getProject() {
		$projectManager = new \model\ProjectManager();
		return $projectManager->getProject($this->getProjectId());
	}

}
