<?php
/**
 * BaseTrainingManager
 * Generated by Tyneo Base Tools
 *
 * @package     model
 * @author      Samuel Kauffmann <skauffmann@tyneo.net>
 * @copyright   Copyright (c) 2011, Samuel Kauffmann
 * @link        http://www.tyneo.net
 * @filesource	BaseTrainingManager.class.php
 */
namespace model\base;

abstract class BaseTrainingManager extends AbstractBaseObjectManager {
	public function __construct(\framework\ApplicationContext $context) {
		parent::__construct($context);
		$this->setTableName('training');
	}

	public function getTrainings() {
		$query = new \framework\query\QueryBuilder();
		$query->addSelect($this->getTableName().'.*');
		$query->addTable($this->getTableName());
		$results = $this->database->query($query->toSQL());
		return $this->getObjectsFromResult($results);
	}


	/**
	 * Returns a limited and filter number of Trainings	 *
	 * @param $start Number Index where we start to display Trainings (by default 0)
	 * @param $maxperpage Number Maximum number of item per page
	 * @param $filter String null or a Training filter
	 */
	public function getLimitedTrainings($start, $maxperpage, $filter) {
		if($maxperpage == null) $maxperpage = $this->context->getConfiguration()->get('max_per_page', 25);
		if($start == null) $start = 0;

		$query = new \framework\query\QueryBuilder();
		$query->addSelect($this->getTableName().'.*');
		$query->addTable($this->getTableName());

		if($filter != null) {
			$f = new \model\TrainingFilter($filter);
			$f->apply($query);
		}

		$query->setStart($start)->setMaxPerPage($maxperpage);

		$results = $this->database->query($query->toSQL());
		return $this->getObjectsFromResult($results);
	}

	public function countLimitedTrainings($filter) {
		$query = new \framework\query\QueryBuilder();
		$query->addSelectCount($this->getTableName().'.id', 'total', true);
		$query->addTable($this->getTableName());

		if($filter != null) {
			$f = new \model\TrainingFilter($filter);
			$f->apply($query);
		}

		return $this->database->queryUniqueObject($query->toSQL())->total;
	}

	public function countTrainings() {
		$query = new \framework\query\QueryBuilder();
		$query->addSelectCount($this->getTableName().'.id', 'total', true);
		$query->addTable($this->getTableName());
		return $this->database->queryUniqueObject($query->toSQL())->total;
	}

	public function getTraining($id) {
		$query = new \framework\query\QueryBuilder();
		$query->addSelect($this->getTableName().'.*');
		$query->addTable($this->getTableName());
		if(!is_array($id)) {
			$query->addWhere($this->getTableName().'.id', \framework\query\operator\Operator::EQUAL, $id);
		} else {
			foreach ($id as $key => $value) {
				$query->addWhere($key, \framework\query\operator\Operator::EQUAL, $value);
			}
		}
		$object = $this->database->queryUniqueObject($query->toSQL());
		if($object != null) {
			return $this->getObjectFromRow($object);
		}
		return null;
	}

	protected function getUpdateQuery(\model\Training $obj) {
		$query = new \framework\query\UpdateBuilder($this->getTableName());
					$query->setField('id', $obj->getId());
							$query->setField('slug', $obj->getSlug());
							$query->setField('name', $obj->getName());
							$query->setField('category', $obj->getCategory());
							$query->setField('objective', $obj->getObjective());
							$query->setField('requirements', $obj->getRequirements());
							$query->setField('recipient', $obj->getRecipient());
							$query->setField('agenda', $obj->getAgenda());
							$query->setField('duration', $obj->getDuration());
							$query->setField('formative', $obj->getFormative());
							$query->setField('state', $obj->getState());
							$query->setField('created_date', $obj->getCreatedDate());
							$query->setField('updated_date', 'CURDATE()', true);

		foreach ($this->getIdFields() as $id) {
			$method = 'get'.$this->slugify($id);
			$query->addWhere($id, \framework\query\operator\Operator::EQUAL, $obj->$method());
		}
		return $query;
	}

	protected function update(\model\Training $obj) {
		$query = $this->getUpdateQuery($obj);
		return $this->database->execute($query->toSQL());
	}

	protected function getCreateQuery(\model\Training $obj) {
		$query = new \framework\query\CreateBuilder($this->getTableName());
				$query->setField('id', $obj->getId());
					$query->setField('slug', $obj->getSlug());
					$query->setField('name', $obj->getName());
					$query->setField('category', $obj->getCategory());
					$query->setField('objective', $obj->getObjective());
					$query->setField('requirements', $obj->getRequirements());
					$query->setField('recipient', $obj->getRecipient());
					$query->setField('agenda', $obj->getAgenda());
					$query->setField('duration', $obj->getDuration());
					$query->setField('formative', $obj->getFormative());
					$query->setField('state', $obj->getState());
					$query->setField('created_date', 'CURDATE()', true);
					$query->setField('updated_date', 'CURDATE()', true);

		return $query;
	}

	protected function create(\model\Training $obj) {
		$query = $this->getCreateQuery($obj);

		if($this->database->execute($query->toSQL())) {
			$obj->setNew(false);
			return true;
		}
		return false;
	}

	public function delete(\model\Training $obj) {
		$query = new \framework\query\DeleteBuilder($this->getTableName());
		foreach ($this->getIdFields() as $id) {
			$method = 'get'.$this->slugify($id);
			$query->addWhere($id, \framework\query\operator\Operator::EQUAL, $obj->$method());
		}
		if($this->database->execute($query->toSQL())) {
			return true;
		}
		return false;
	}

	protected function getObjectFromRow($row) {
		$object = new \model\Training();
			$object->setId(\framework\utility\String::fromSQL($row->id));
			$object->setSlug(\framework\utility\String::fromSQL($row->slug));
			$object->setName(\framework\utility\String::fromSQL($row->name));
			$object->setCategory(\framework\utility\String::fromSQL($row->category));
			$object->setObjective(\framework\utility\String::fromSQL($row->objective));
			$object->setRequirements(\framework\utility\String::fromSQL($row->requirements));
			$object->setRecipient(\framework\utility\String::fromSQL($row->recipient));
			$object->setAgenda(\framework\utility\String::fromSQL($row->agenda));
			$object->setDuration(\framework\utility\String::fromSQL($row->duration));
			$object->setFormative(\framework\utility\String::fromSQL($row->formative));
			$object->setState(\framework\utility\String::fromSQL($row->state));
			$object->setCreatedDate(\framework\utility\String::fromSQL($row->created_date));
			$object->setUpdatedDate(\framework\utility\String::fromSQL($row->updated_date));

		$object->setNew(false);
		return $object;
	}

}
