<?php
/**
 * BaseProjectManager
 * Generated by Tyneo Base Tools
 *
 * @package     model
 * @author      Samuel Kauffmann <skauffmann@tyneo.net>
 * @copyright   Copyright (c) 2011, Samuel Kauffmann
 * @link        http://www.tyneo.net
 * @filesource	BaseProjectManager.class.php
 */
namespace model\base;

abstract class BaseProjectManager extends AbstractBaseObjectManager {
	public function __construct(\framework\ApplicationContext $context) {
		parent::__construct($context);
		$this->setTableName('project');
	}

	public function getProjects() {
		$query = new \framework\query\QueryBuilder();
		$query->addSelect($this->getTableName().'.*');
		$query->addTable($this->getTableName());
		$results = $this->database->query($query->toSQL());
		return $this->getObjectsFromResult($results);
	}


	/**
	 * Returns a limited and filter number of Projects	 *
	 * @param $start Number Index where we start to display Projects (by default 0)
	 * @param $maxperpage Number Maximum number of item per page
	 * @param $filter String null or a Project filter
	 */
	public function getLimitedProjects($start, $maxperpage, $filter) {
		if($maxperpage == null) $maxperpage = $this->context->getConfiguration()->get('max_per_page', 25);
		if($start == null) $start = 0;

		$query = new \framework\query\QueryBuilder();
		$query->addSelect($this->getTableName().'.*');
		$query->addTable($this->getTableName());

		if($filter != null) {
			$f = new \model\ProjectFilter($filter);
			$f->apply($query);
		}

		$query->setStart($start)->setMaxPerPage($maxperpage);

		$results = $this->database->query($query->toSQL());
		return $this->getObjectsFromResult($results);
	}

	public function countLimitedProjects($filter) {
		$query = new \framework\query\QueryBuilder();
		$query->addSelectCount($this->getTableName().'.id', 'total', true);
		$query->addTable($this->getTableName());

		if($filter != null) {
			$f = new \model\ProjectFilter($filter);
			$f->apply($query);
		}

		return $this->database->queryUniqueObject($query->toSQL())->total;
	}

	public function countProjects() {
		$query = new \framework\query\QueryBuilder();
		$query->addSelectCount($this->getTableName().'.id', 'total', true);
		$query->addTable($this->getTableName());
		return $this->database->queryUniqueObject($query->toSQL())->total;
	}

	public function getProject($id) {
		$query = new \framework\query\QueryBuilder();
		$query->addSelect($this->getTableName().'.*');
		$query->addTable($this->getTableName());
		if(!is_array($id)) {
			$query->addWhere($this->getTableName().'.id', \framework\query\operator\Operator::EQUAL, $id);
		} else {
			foreach ($id as $key => $value) {
				$query->addWhere($key, \framework\query\operator\Operator::EQUAL, $value);
			}
		}
		$object = $this->database->queryUniqueObject($query->toSQL());
		if($object != null) {
			return $this->getObjectFromRow($object);
		}
		return null;
	}

	protected function getUpdateQuery(\model\Project $obj) {
		$query = new \framework\query\UpdateBuilder($this->getTableName());
					$query->setField('id', $obj->getId());
							$query->setField('name', $obj->getName());
							$query->setField('description', $obj->getDescription());
							$query->setField('start_date', $obj->getStartDate());
							$query->setField('end_date', $obj->getEndDate());
							$query->setField('is_archived', $obj->getIsArchived());
							$query->setField('created_date', $obj->getCreatedDate());
							$query->setField('updated_date', 'CURDATE()', true);

		foreach ($this->getIdFields() as $id) {
			$method = 'get'.$this->slugify($id);
			$query->addWhere($id, \framework\query\operator\Operator::EQUAL, $obj->$method());
		}
		return $query;
	}

	protected function update(\model\Project $obj) {
		$query = $this->getUpdateQuery($obj);
		return $this->database->execute($query->toSQL());
	}

	protected function getCreateQuery(\model\Project $obj) {
		$query = new \framework\query\CreateBuilder($this->getTableName());
				$query->setField('id', $obj->getId());
					$query->setField('name', $obj->getName());
					$query->setField('description', $obj->getDescription());
					$query->setField('start_date', $obj->getStartDate());
					$query->setField('end_date', $obj->getEndDate());
					$query->setField('is_archived', $obj->getIsArchived());
					$query->setField('created_date', 'CURDATE()', true);
					$query->setField('updated_date', 'CURDATE()', true);

		return $query;
	}

	protected function create(\model\Project $obj) {
		$query = $this->getCreateQuery($obj);

		if($this->database->execute($query->toSQL())) {
			$obj->setNew(false);
			return true;
		}
		return false;
	}

	public function delete(\model\Project $obj) {
		$query = new \framework\query\DeleteBuilder($this->getTableName());
		foreach ($this->getIdFields() as $id) {
			$method = 'get'.$this->slugify($id);
			$query->addWhere($id, \framework\query\operator\Operator::EQUAL, $obj->$method());
		}
		if($this->database->execute($query->toSQL())) {
			return true;
		}
		return false;
	}

	protected function getObjectFromRow($row) {
		$object = new \model\Project();
			$object->setId(\framework\utility\String::fromSQL($row->id));
			$object->setName(\framework\utility\String::fromSQL($row->name));
			$object->setDescription(\framework\utility\String::fromSQL($row->description));
			$object->setStartDate(\framework\utility\String::fromSQL($row->start_date));
			$object->setEndDate(\framework\utility\String::fromSQL($row->end_date));
			$object->setIsArchived(\framework\utility\String::fromSQL($row->is_archived));
			$object->setCreatedDate(\framework\utility\String::fromSQL($row->created_date));
			$object->setUpdatedDate(\framework\utility\String::fromSQL($row->updated_date));

		$object->setNew(false);
		return $object;
	}

}
